//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoCaja
    {
        public short aq_empresa { get; set; }
        public int aq_IdCierreCaja { get; set; }
        public int aq_IdArqueoCaja { get; set; }
        public string aq_Moneda { get; set; }
        public string aq_PresentacionMoneda { get; set; }
        public string aq_Denominacion { get; set; }
        public int aq_Cantidad { get; set; }
        public decimal aq_MontoTotal { get; set; }
        public System.DateTime aq_fechaing { get; set; }
        public Nullable<System.DateTime> aq_fechamod { get; set; }
        public string aq_usuarioing { get; set; }
        public string aq_usuariomod { get; set; }
        public string aq_maquinaing { get; set; }
        public string aq_maquinamod { get; set; }
        public int aq_estado { get; set; }
        public byte[] aq_timestamp { get; set; }
    }
}
