//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public short bt_empresa { get; set; }
        public string bt_tipoOperacion { get; set; }
        public string bt_nombreTabla { get; set; }
        public string bt_idRegistro { get; set; }
        public string bt_nombreCampo { get; set; }
        public string bt_datoActual { get; set; }
        public string bt_datoAnterior { get; set; }
        public string bt_Comentario { get; set; }
        public System.DateTime bt_fechaing { get; set; }
        public Nullable<System.DateTime> bt_fechamod { get; set; }
        public string bt_usuarioing { get; set; }
        public string bt_usuariomod { get; set; }
        public string bt_maquinaing { get; set; }
        public string bt_maquinamod { get; set; }
        public int bt_estado { get; set; }
        public byte[] bt_timestamp { get; set; }
    }
}
