//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CabCatalogo
    {
        public short cc_empresa { get; set; }
        public int cc_IdCatalogo { get; set; }
        [Required(ErrorMessage = "Nombre del catalogo es requerido")]
        public string cc_nombre { get; set; }
        [Required(ErrorMessage = "Valor 1 es requerido")]
        public string cc_nomVal1 { get; set; }
        public string cc_nomVal2 { get; set; }
        public string cc_nomVal3 { get; set; }
        public System.DateTime cc_fechaing { get; set; }
        public Nullable<System.DateTime> cc_fechamod { get; set; }
        public string cc_usuarioing { get; set; }
        public string cc_usuariomod { get; set; }
        public string cc_maquinaing { get; set; }
        public string cc_maquinamod { get; set; }
        public int cc_estado { get; set; }
        public byte[] cc_timestamp { get; set; }
    }
}
