//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreDiario
    {
        public short cd_empresa { get; set; }
        public int cd_IdSucursal { get; set; }
        public int cd_IdCierreDiario { get; set; }
        public System.DateTime cd_FechaCierreDiario { get; set; }
        public string cd_estCierreDiario { get; set; }
        public System.DateTime cd_fechaing { get; set; }
        public Nullable<System.DateTime> cd_fechamod { get; set; }
        public string cd_usuarioing { get; set; }
        public string cd_usuariomod { get; set; }
        public string cd_maquinaing { get; set; }
        public string cd_maquinamod { get; set; }
        public int cd_estado { get; set; }
        public byte[] cd_timestamp { get; set; }
    }
}
