//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierreCaja
    {
        public short cj_empresa { get; set; }
        public int cj_IdCierreCaja { get; set; }
        public string cj_Terminal { get; set; }
        public int cj_IdSucursal { get; set; }
        public System.DateTime cj_FechaHoraCierre { get; set; }
        public string cj_Moneda { get; set; }
        public Nullable<decimal> cj_SaldoAnterior { get; set; }
        public Nullable<decimal> cj_EntradasEfectivo { get; set; }
        public Nullable<decimal> cj_SalidasEfectivo { get; set; }
        public Nullable<decimal> cj_EfectivoTeorico { get; set; }
        public Nullable<decimal> cj_EfectivoFisico { get; set; }
        public Nullable<decimal> cj_AjusteEfectivo { get; set; }
        public Nullable<decimal> cj_ChequeTeorico { get; set; }
        public Nullable<decimal> cj_ChequeFisico { get; set; }
        public Nullable<decimal> cj_AjusteCheque { get; set; }
        public Nullable<decimal> cj_TarjetaTeorico { get; set; }
        public Nullable<decimal> cj_TarjetaFisico { get; set; }
        public Nullable<decimal> cj_AjusteTarjeta { get; set; }
        public Nullable<decimal> cj_Descuadre { get; set; }
        public Nullable<decimal> cj_RetiroEfectivoAdmin { get; set; }
        public Nullable<decimal> cj_SaldoActual { get; set; }
        public string cj_estCierreCaja { get; set; }
        public Nullable<decimal> cj_TotalVenta { get; set; }
        public Nullable<decimal> cj_TotalPropina { get; set; }
        public System.DateTime cj_fechaing { get; set; }
        public Nullable<System.DateTime> cj_fechamod { get; set; }
        public string cj_usuarioing { get; set; }
        public string cj_usuariomod { get; set; }
        public string cj_maquinaing { get; set; }
        public string cj_maquinamod { get; set; }
        public int cj_estado { get; set; }
        public byte[] cj_timestamp { get; set; }
    }
}
