//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public short cl_empresa { get; set; }
        public int cl_cliente { get; set; }
        [Required(ErrorMessage = "Tipo de cliente es requerido")]
        public string cl_tipoCliente { get; set; }
        [Required(ErrorMessage = "Clasificación del cliente es requerido")]
        public string cl_ClasificacionCliente { get; set; }
        [Required(ErrorMessage = "Tipo de identificación es requerido")]
        public string cl_tipoident { get; set; }
        [Required(ErrorMessage = "Identificación es requerido")]
        public string cl_identifica { get; set; }
        public string cl_nit { get; set; }
        [Required(ErrorMessage = "Primer nombre es requerido")]
        public string cl_nombre1 { get; set; }
        public string cl_nombre2 { get; set; }
        public string cl_nombre3 { get; set; }
        [Required(ErrorMessage = "Primer apellido es requerido")]
        public string cl_apellido1 { get; set; }
        public string cl_apellido2 { get; set; }
        public string cl_apecasada { get; set; }
        [Required(ErrorMessage = "Nombre largo es requerido")]
        public string cl_nombrelargo { get; set; }
        [Required(ErrorMessage = "Genero es requerido")]
        public string cl_genero { get; set; }
        [Required(ErrorMessage = "FEcha de nacimiento es requerido")]
        public Nullable<System.DateTime> cl_fechanac { get; set; }
        public string cl_ocupacion { get; set; }
        public string cl_estadocivil { get; set; }
        public Nullable<int> cl_RecibePublicidad { get; set; }
        public System.DateTime cl_fechaing { get; set; }
        public Nullable<System.DateTime> cl_fechamod { get; set; }
        public string cl_usuarioing { get; set; }
        public string cl_usuariomod { get; set; }
        public string cl_maquinaing { get; set; }
        public string cl_maquinamod { get; set; }
        public int cl_estado { get; set; }
        public byte[] cl_timestamp { get; set; }
    }
}
