//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contacto
    {
        public short cn_empresa { get; set; }
        public int cn_idContacto { get; set; }
        public string cn_tipoAsociado { get; set; }
        public int cn_asociado { get; set; }
        [Required(ErrorMessage = "Tipo de contacto es requerido")]
        public string cn_tipoContacto { get; set; }
        [Required(ErrorMessage = "Contacto es requerido")]
        public string cn_Contacto { get; set; }
        public string cn_Contacto2 { get; set; }
        public System.DateTime cn_fechaing { get; set; }
        public Nullable<System.DateTime> cn_fechamod { get; set; }
        public string cn_usuarioing { get; set; }
        public string cn_usuariomod { get; set; }
        public string cn_maquinaing { get; set; }
        public string cn_maquinamod { get; set; }
        public int cn_estado { get; set; }
        public byte[] cn_timestamp { get; set; }
    }
}
