//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaXCobrar
    {
        public short cc_empresa { get; set; }
        public int cc_IdCuentaXCobrar { get; set; }
        public int cc_Cliente { get; set; }
        public decimal cc_Saldo { get; set; }
        public System.DateTime cc_fechaUltMov { get; set; }
        public decimal cc_MontoUltMov { get; set; }
        public string cc_estCuentaXCobrar { get; set; }
        public System.DateTime cc_fechaing { get; set; }
        public Nullable<System.DateTime> cc_fechamod { get; set; }
        public string cc_usuarioing { get; set; }
        public string cc_usuariomod { get; set; }
        public string cc_maquinaing { get; set; }
        public string cc_maquinamod { get; set; }
        public int cc_estado { get; set; }
        public byte[] cc_timestamp { get; set; }
    }
}
