//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaXPagar
    {
        public short cp_empresa { get; set; }
        public int cp_IdCuentaXPagar { get; set; }
        public int cp_Proveedor { get; set; }
        public decimal cp_Saldo { get; set; }
        public System.DateTime cp_fechaUltMov { get; set; }
        public decimal cp_MontoUltMov { get; set; }
        public string cp_estCuentaXPagar { get; set; }
        public System.DateTime cp_fechaing { get; set; }
        public Nullable<System.DateTime> cp_fechamod { get; set; }
        public string cp_usuarioing { get; set; }
        public string cp_usuariomod { get; set; }
        public string cp_maquinaing { get; set; }
        public string cp_maquinamod { get; set; }
        public int cp_estado { get; set; }
        public byte[] cp_timestamp { get; set; }
    }
}
