//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public short ds_empresa { get; set; }
        public int ds_IdDescuento { get; set; }
        public int ds_IdSucursal { get; set; }
        public string ds_TipoDescuento { get; set; }
        public string ds_Descripcion { get; set; }
        public int ds_Porcentaje { get; set; }
        public decimal ds_Cantidad { get; set; }
        public int ds_IdDoc { get; set; }
        public int ds_IdMov { get; set; }
        public int ds_IdAutorizacion { get; set; }
        public Nullable<int> ds_IdMovDescuento { get; set; }
        public string ds_Comentario { get; set; }
        public System.DateTime ds_fechaing { get; set; }
        public Nullable<System.DateTime> ds_fechamod { get; set; }
        public string ds_usuarioing { get; set; }
        public string ds_usuariomod { get; set; }
        public string ds_maquinaing { get; set; }
        public string ds_maquinamod { get; set; }
        public int ds_estado { get; set; }
        public byte[] ds_timestamp { get; set; }
    }
}
