//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCierreCaja
    {
        public short dj_empresa { get; set; }
        public int dj_IdCierreCaja { get; set; }
        public int dj_IdDetalleCierreCaja { get; set; }
        public string dj_IdFormaPago { get; set; }
        public decimal dj_Monto { get; set; }
        public System.DateTime dj_fechaing { get; set; }
        public Nullable<System.DateTime> dj_fechamod { get; set; }
        public string dj_usuarioing { get; set; }
        public string dj_usuariomod { get; set; }
        public string dj_maquinaing { get; set; }
        public string dj_maquinamod { get; set; }
        public int dj_estado { get; set; }
        public byte[] dj_timestamp { get; set; }
    }
}
