//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetCatalogo
    {
        public short cd_empresa { get; set; }
        public int cd_IdCatalogo { get; set; }
        [Required(ErrorMessage = "Codigo es requerido")]
        public string cd_codigo { get; set; }
        [Required(ErrorMessage = "valor es requerido")]
        public string cd_valor { get; set; }
        public string cd_valor1 { get; set; }
        public string cd_valor2 { get; set; }
        public string cd_valor3 { get; set; }
        public System.DateTime cd_fechaing { get; set; }
        public Nullable<System.DateTime> cd_fechamod { get; set; }
        public string cd_usuarioing { get; set; }
        public string cd_usuariomod { get; set; }
        public string cd_maquinaing { get; set; }
        public string cd_maquinamod { get; set; }
        public int cd_estado { get; set; }
        public byte[] cd_timestamp { get; set; }
    }
}
