//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public short dm_empresa { get; set; }
        public int dm_IdSucursal { get; set; }
        public int dm_IdDoc { get; set; }
        public string dm_TipoDocumento { get; set; }
        public string dm_TipoAsociado { get; set; }
        public Nullable<int> dm_asociado { get; set; }
        public string dm_NombreAsociado { get; set; }
        public string dm_DireccionAsociado { get; set; }
        public string dm_Nit { get; set; }
        public decimal dm_subtotal { get; set; }
        public decimal dm_descuento { get; set; }
        public decimal dm_total { get; set; }
        public string dm_SerieDoc { get; set; }
        public string dm_NoDocumento { get; set; }
        public System.DateTime dm_fechaDoc { get; set; }
        public string dm_EstDocumento { get; set; }
        public string dm_Terminal { get; set; }
        public string dm_MotivoAnulacion { get; set; }
        public string dm_MotivoNCND { get; set; }
        public string dm_Comentario { get; set; }
        public Nullable<int> dm_IdDocAnulado { get; set; }
        public Nullable<int> dm_IdCierreDiario { get; set; }
        public System.DateTime dm_fechaing { get; set; }
        public Nullable<System.DateTime> dm_fechamod { get; set; }
        public string dm_usuarioing { get; set; }
        public string dm_usuariomod { get; set; }
        public string dm_maquinaing { get; set; }
        public string dm_maquinamod { get; set; }
        public int dm_estado { get; set; }
        public byte[] dm_timestamp { get; set; }
    }
}
