//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public short em_empresa { get; set; }
        public int em_IdEmpleado { get; set; }
        public string em_tipoEmpleado { get; set; }
        public string em_tipoIdentifica { get; set; }
        public string em_Identifica { get; set; }
        public string em_Nit { get; set; }
        public string em_Nombre1 { get; set; }
        public string em_Nombre2 { get; set; }
        public string em_Nombre3 { get; set; }
        public string em_Apellido1 { get; set; }
        public string em_Apellido2 { get; set; }
        public string em_ApeCasada { get; set; }
        public string em_nombrelargo { get; set; }
        public string em_Alias { get; set; }
        public string em_genero { get; set; }
        public System.DateTime em_FechaNac { get; set; }
        public string em_ocupacion { get; set; }
        public string em_estadoCivil { get; set; }
        public string em_estEmpleado { get; set; }
        public System.DateTime em_FechaIngreso { get; set; }
        public Nullable<System.DateTime> em_FechaSalida { get; set; }
        public decimal em_SueldoBase { get; set; }
        public decimal em_Bonificacion { get; set; }
        public System.DateTime em_fechaing { get; set; }
        public Nullable<System.DateTime> em_fechamod { get; set; }
        public string em_usuarioing { get; set; }
        public string em_usuariomod { get; set; }
        public string em_maquinaing { get; set; }
        public string em_maquinamod { get; set; }
        public int em_estado { get; set; }
        public byte[] em_timestamp { get; set; }
    }
}
