//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencia
    {
        public short ex_empresa { get; set; }
        public int ex_IdSucursal { get; set; }
        public int ex_IdExistencia { get; set; }
        public int ex_TipoProducto { get; set; }
        public int ex_IdProd { get; set; }
        public int ex_cantidad { get; set; }
        public decimal ex_precioUnitario { get; set; }
        public Nullable<System.DateTime> ex_FechaCaducidad { get; set; }
        public System.DateTime ex_fechaing { get; set; }
        public Nullable<System.DateTime> ex_fechamod { get; set; }
        public string ex_usuarioing { get; set; }
        public string ex_usuariomod { get; set; }
        public string ex_maquinaing { get; set; }
        public string ex_maquinamod { get; set; }
        public int ex_estado { get; set; }
        public byte[] ex_timestamp { get; set; }
    }
}
