//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public short fo_empresa { get; set; }
        public int fo_IdFoto { get; set; }
        public string fo_TipoAsociado { get; set; }
        public int fo_asociado { get; set; }
        public byte[] fo_foto { get; set; }
        public System.DateTime fo_fechaing { get; set; }
        public Nullable<System.DateTime> fo_fechamod { get; set; }
        public string fo_usuarioing { get; set; }
        public string fo_usuariomod { get; set; }
        public string fo_maquinaing { get; set; }
        public string fo_maquinamod { get; set; }
        public int fo_estado { get; set; }
        public byte[] fo_timestamp { get; set; }
    }
}
