//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioSucursal
    {
        public short hs_empresa { get; set; }
        public int hs_IdSucursal { get; set; }
        public string hs_dia { get; set; }
        public string hs_Hora { get; set; }
        public System.DateTime hs_fechaing { get; set; }
        public Nullable<System.DateTime> hs_fechamod { get; set; }
        public string hs_usuarioing { get; set; }
        public string hs_usuariomod { get; set; }
        public string hs_maquinaing { get; set; }
        public string hs_maquinamod { get; set; }
        public int hs_estado { get; set; }
        public byte[] hs_timestamp { get; set; }
    }
}
