//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioEmpleado
    {
        public short he_empresa { get; set; }
        public int he_IdHorario { get; set; }
        public int he_diaSemana { get; set; }
        public int he_IdEmpleado { get; set; }
        public System.DateTime he_fechaing { get; set; }
        public Nullable<System.DateTime> he_fechamod { get; set; }
        public string he_usuarioing { get; set; }
        public string he_usuariomod { get; set; }
        public string he_maquinaing { get; set; }
        public string he_maquinamod { get; set; }
        public int he_estado { get; set; }
        public byte[] he_timestamp { get; set; }
        public int he_CodHorarioEmpleado { get; set; }
    }
}
