//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huella
    {
        public short hu_empresa { get; set; }
        public int hu_IdHuella { get; set; }
        public string hu_TipoAsociado { get; set; }
        public int hu_asociado { get; set; }
        public byte[] hu_huella { get; set; }
        public string hu_mano { get; set; }
        public string hu_dedo { get; set; }
        public Nullable<int> hu_huella_long { get; set; }
        public System.DateTime hu_fechaing { get; set; }
        public Nullable<System.DateTime> hu_fechamod { get; set; }
        public string hu_usuarioing { get; set; }
        public string hu_usuariomod { get; set; }
        public string hu_maquinaing { get; set; }
        public string hu_maquinamod { get; set; }
        public int hu_estado { get; set; }
        public byte[] hu_timestamp { get; set; }
    }
}
