//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public short im_empresa { get; set; }
        public int im_CodImagen { get; set; }
        public string im_NombreImagen { get; set; }
        public byte[] im_imagen { get; set; }
        public string im_estImagen { get; set; }
        public System.DateTime im_fechaing { get; set; }
        public Nullable<System.DateTime> im_fechamod { get; set; }
        public string im_usuarioing { get; set; }
        public string im_usuariomod { get; set; }
        public string im_maquinaing { get; set; }
        public string im_maquinamod { get; set; }
        public int im_estado { get; set; }
        public byte[] im_timestamp { get; set; }
    }
}
