//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SSS_COMPLEMENTOSEntities : DbContext
    {
        public SSS_COMPLEMENTOSEntities()
            : base("name=SSS_COMPLEMENTOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CabCatalogo> CabCatalogoes { get; set; }
        public virtual DbSet<Imagen> Imagens { get; set; }
        public virtual DbSet<Secuencial> Secuencials { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<DetCatalogo> DetCatalogoes { get; set; }
        public virtual DbSet<vw_catalogo> vw_catalogo { get; set; }
    
        public virtual int sp_ABC_Bitacora(Nullable<short> bt_empresa, string bt_opcion, string bt_tipoOperacion, string bt_nombreTabla, string bt_IdRegistro, string bt_nombreCampo, string bt_datoActual, string bt_datoAnterior, string bt_comentario, string bt_usuario, byte[] bt_timestamp, ObjectParameter error)
        {
            var bt_empresaParameter = bt_empresa.HasValue ?
                new ObjectParameter("bt_empresa", bt_empresa) :
                new ObjectParameter("bt_empresa", typeof(short));
    
            var bt_opcionParameter = bt_opcion != null ?
                new ObjectParameter("bt_opcion", bt_opcion) :
                new ObjectParameter("bt_opcion", typeof(string));
    
            var bt_tipoOperacionParameter = bt_tipoOperacion != null ?
                new ObjectParameter("bt_tipoOperacion", bt_tipoOperacion) :
                new ObjectParameter("bt_tipoOperacion", typeof(string));
    
            var bt_nombreTablaParameter = bt_nombreTabla != null ?
                new ObjectParameter("bt_nombreTabla", bt_nombreTabla) :
                new ObjectParameter("bt_nombreTabla", typeof(string));
    
            var bt_IdRegistroParameter = bt_IdRegistro != null ?
                new ObjectParameter("bt_IdRegistro", bt_IdRegistro) :
                new ObjectParameter("bt_IdRegistro", typeof(string));
    
            var bt_nombreCampoParameter = bt_nombreCampo != null ?
                new ObjectParameter("bt_nombreCampo", bt_nombreCampo) :
                new ObjectParameter("bt_nombreCampo", typeof(string));
    
            var bt_datoActualParameter = bt_datoActual != null ?
                new ObjectParameter("bt_datoActual", bt_datoActual) :
                new ObjectParameter("bt_datoActual", typeof(string));
    
            var bt_datoAnteriorParameter = bt_datoAnterior != null ?
                new ObjectParameter("bt_datoAnterior", bt_datoAnterior) :
                new ObjectParameter("bt_datoAnterior", typeof(string));
    
            var bt_comentarioParameter = bt_comentario != null ?
                new ObjectParameter("bt_comentario", bt_comentario) :
                new ObjectParameter("bt_comentario", typeof(string));
    
            var bt_usuarioParameter = bt_usuario != null ?
                new ObjectParameter("bt_usuario", bt_usuario) :
                new ObjectParameter("bt_usuario", typeof(string));
    
            var bt_timestampParameter = bt_timestamp != null ?
                new ObjectParameter("bt_timestamp", bt_timestamp) :
                new ObjectParameter("bt_timestamp", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Bitacora", bt_empresaParameter, bt_opcionParameter, bt_tipoOperacionParameter, bt_nombreTablaParameter, bt_IdRegistroParameter, bt_nombreCampoParameter, bt_datoActualParameter, bt_datoAnteriorParameter, bt_comentarioParameter, bt_usuarioParameter, bt_timestampParameter, error);
        }
    
        public virtual int sp_ABC_CabCatalogo(Nullable<short> cc_empresa, string cc_opcion, ObjectParameter cc_IdCatalogo, string cc_nombre, string cc_nomVal1, string cc_nomVal2, string cc_nomVal3, string cc_usuario, string cc_timestamp, ObjectParameter error)
        {
            var cc_empresaParameter = cc_empresa.HasValue ?
                new ObjectParameter("cc_empresa", cc_empresa) :
                new ObjectParameter("cc_empresa", typeof(short));
    
            var cc_opcionParameter = cc_opcion != null ?
                new ObjectParameter("cc_opcion", cc_opcion) :
                new ObjectParameter("cc_opcion", typeof(string));
    
            var cc_nombreParameter = cc_nombre != null ?
                new ObjectParameter("cc_nombre", cc_nombre) :
                new ObjectParameter("cc_nombre", typeof(string));
    
            var cc_nomVal1Parameter = cc_nomVal1 != null ?
                new ObjectParameter("cc_nomVal1", cc_nomVal1) :
                new ObjectParameter("cc_nomVal1", typeof(string));
    
            var cc_nomVal2Parameter = cc_nomVal2 != null ?
                new ObjectParameter("cc_nomVal2", cc_nomVal2) :
                new ObjectParameter("cc_nomVal2", typeof(string));
    
            var cc_nomVal3Parameter = cc_nomVal3 != null ?
                new ObjectParameter("cc_nomVal3", cc_nomVal3) :
                new ObjectParameter("cc_nomVal3", typeof(string));
    
            var cc_usuarioParameter = cc_usuario != null ?
                new ObjectParameter("cc_usuario", cc_usuario) :
                new ObjectParameter("cc_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("cc_timestamp", Convert.FromBase64String(cc_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_CabCatalogo", cc_empresaParameter, cc_opcionParameter, cc_IdCatalogo, cc_nombreParameter, cc_nomVal1Parameter, cc_nomVal2Parameter, cc_nomVal3Parameter, cc_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_DetCatalogo(Nullable<short> cd_empresa, string cd_opcion, Nullable<int> cd_IdCatalogo, string cd_codigo, string cd_valor, string cd_Valor1, string cd_Valor2, string cd_Valor3, string cd_usuario, String cd_timestamp, ObjectParameter error)
        {
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(short));
    
            var cd_opcionParameter = cd_opcion != null ?
                new ObjectParameter("cd_opcion", cd_opcion) :
                new ObjectParameter("cd_opcion", typeof(string));
    
            var cd_IdCatalogoParameter = cd_IdCatalogo.HasValue ?
                new ObjectParameter("cd_IdCatalogo", cd_IdCatalogo) :
                new ObjectParameter("cd_IdCatalogo", typeof(int));
    
            var cd_codigoParameter = cd_codigo != null ?
                new ObjectParameter("cd_codigo", cd_codigo) :
                new ObjectParameter("cd_codigo", typeof(string));
    
            var cd_valorParameter = cd_valor != null ?
                new ObjectParameter("cd_valor", cd_valor) :
                new ObjectParameter("cd_valor", typeof(string));
    
            var cd_Valor1Parameter = cd_Valor1 != null ?
                new ObjectParameter("cd_Valor1", cd_Valor1) :
                new ObjectParameter("cd_Valor1", typeof(string));
    
            var cd_Valor2Parameter = cd_Valor2 != null ?
                new ObjectParameter("cd_Valor2", cd_Valor2) :
                new ObjectParameter("cd_Valor2", typeof(string));
    
            var cd_Valor3Parameter = cd_Valor3 != null ?
                new ObjectParameter("cd_Valor3", cd_Valor3) :
                new ObjectParameter("cd_Valor3", typeof(string));
    
            var cd_usuarioParameter = cd_usuario != null ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("cd_timestamp", Convert.FromBase64String(cd_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_DetCatalogo", cd_empresaParameter, cd_opcionParameter, cd_IdCatalogoParameter, cd_codigoParameter, cd_valorParameter, cd_Valor1Parameter, cd_Valor2Parameter, cd_Valor3Parameter, cd_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Imagen(Nullable<short> im_empresa, string im_opcion, ObjectParameter im_CodImagen, string im_NombreImagen, byte[] im_imagen, string im_estImagen, string im_usuario, ObjectParameter im_timestamp, ObjectParameter error)
        {
            var im_empresaParameter = im_empresa.HasValue ?
                new ObjectParameter("im_empresa", im_empresa) :
                new ObjectParameter("im_empresa", typeof(short));
    
            var im_opcionParameter = im_opcion != null ?
                new ObjectParameter("im_opcion", im_opcion) :
                new ObjectParameter("im_opcion", typeof(string));
    
            var im_NombreImagenParameter = im_NombreImagen != null ?
                new ObjectParameter("im_NombreImagen", im_NombreImagen) :
                new ObjectParameter("im_NombreImagen", typeof(string));
    
            var im_imagenParameter = im_imagen != null ?
                new ObjectParameter("im_imagen", im_imagen) :
                new ObjectParameter("im_imagen", typeof(byte[]));
    
            var im_estImagenParameter = im_estImagen != null ?
                new ObjectParameter("im_estImagen", im_estImagen) :
                new ObjectParameter("im_estImagen", typeof(string));
    
            var im_usuarioParameter = im_usuario != null ?
                new ObjectParameter("im_usuario", im_usuario) :
                new ObjectParameter("im_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Imagen", im_empresaParameter, im_opcionParameter, im_CodImagen, im_NombreImagenParameter, im_imagenParameter, im_estImagenParameter, im_usuarioParameter, im_timestamp, error);
        }
    
        public virtual int sp_Altas_Secuencial(Nullable<short> sc_empresa, string sc_tabla, string sc_DataBase, Nullable<int> sc_centralizado, string sc_usuario, ObjectParameter error)
        {
            var sc_empresaParameter = sc_empresa.HasValue ?
                new ObjectParameter("sc_empresa", sc_empresa) :
                new ObjectParameter("sc_empresa", typeof(short));
    
            var sc_tablaParameter = sc_tabla != null ?
                new ObjectParameter("sc_tabla", sc_tabla) :
                new ObjectParameter("sc_tabla", typeof(string));
    
            var sc_DataBaseParameter = sc_DataBase != null ?
                new ObjectParameter("sc_DataBase", sc_DataBase) :
                new ObjectParameter("sc_DataBase", typeof(string));
    
            var sc_centralizadoParameter = sc_centralizado.HasValue ?
                new ObjectParameter("sc_centralizado", sc_centralizado) :
                new ObjectParameter("sc_centralizado", typeof(int));
    
            var sc_usuarioParameter = sc_usuario != null ?
                new ObjectParameter("sc_usuario", sc_usuario) :
                new ObjectParameter("sc_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Altas_Secuencial", sc_empresaParameter, sc_tablaParameter, sc_DataBaseParameter, sc_centralizadoParameter, sc_usuarioParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_CabCatalogo_Result> sp_Busqueda_CabCatalogo(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> cc_empresa, Nullable<int> cc_IdCatalogo, string cc_nombre, string cc_nomVal1, string cc_nomVal2, string cc_nomVal3, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var cc_empresaParameter = cc_empresa.HasValue ?
                new ObjectParameter("cc_empresa", cc_empresa) :
                new ObjectParameter("cc_empresa", typeof(short));
    
            var cc_IdCatalogoParameter = cc_IdCatalogo.HasValue ?
                new ObjectParameter("cc_IdCatalogo", cc_IdCatalogo) :
                new ObjectParameter("cc_IdCatalogo", typeof(int));
    
            var cc_nombreParameter = cc_nombre != null ?
                new ObjectParameter("cc_nombre", cc_nombre) :
                new ObjectParameter("cc_nombre", typeof(string));
    
            var cc_nomVal1Parameter = cc_nomVal1 != null ?
                new ObjectParameter("cc_nomVal1", cc_nomVal1) :
                new ObjectParameter("cc_nomVal1", typeof(string));
    
            var cc_nomVal2Parameter = cc_nomVal2 != null ?
                new ObjectParameter("cc_nomVal2", cc_nomVal2) :
                new ObjectParameter("cc_nomVal2", typeof(string));
    
            var cc_nomVal3Parameter = cc_nomVal3 != null ?
                new ObjectParameter("cc_nomVal3", cc_nomVal3) :
                new ObjectParameter("cc_nomVal3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_CabCatalogo_Result>("sp_Busqueda_CabCatalogo", tipoBusquedaParameter, busquedaParameter, cc_empresaParameter, cc_IdCatalogoParameter, cc_nombreParameter, cc_nomVal1Parameter, cc_nomVal2Parameter, cc_nomVal3Parameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Catalogo_Result> sp_Busqueda_Catalogo(Nullable<short> ca_empresa, Nullable<int> ca_IdCatalogo, string ca_NomCatalogo, string ca_CodCatalogo, string ca_Descripcion, string ca_Valor1, string ca_Valor2, string ca_Valor3, ObjectParameter error)
        {
            var ca_empresaParameter = ca_empresa.HasValue ?
                new ObjectParameter("ca_empresa", ca_empresa) :
                new ObjectParameter("ca_empresa", typeof(short));
    
            var ca_IdCatalogoParameter = ca_IdCatalogo.HasValue ?
                new ObjectParameter("ca_IdCatalogo", ca_IdCatalogo) :
                new ObjectParameter("ca_IdCatalogo", typeof(int));
    
            var ca_NomCatalogoParameter = ca_NomCatalogo != null ?
                new ObjectParameter("ca_NomCatalogo", ca_NomCatalogo) :
                new ObjectParameter("ca_NomCatalogo", typeof(string));
    
            var ca_CodCatalogoParameter = ca_CodCatalogo != null ?
                new ObjectParameter("ca_CodCatalogo", ca_CodCatalogo) :
                new ObjectParameter("ca_CodCatalogo", typeof(string));
    
            var ca_DescripcionParameter = ca_Descripcion != null ?
                new ObjectParameter("ca_Descripcion", ca_Descripcion) :
                new ObjectParameter("ca_Descripcion", typeof(string));
    
            var ca_Valor1Parameter = ca_Valor1 != null ?
                new ObjectParameter("ca_Valor1", ca_Valor1) :
                new ObjectParameter("ca_Valor1", typeof(string));
    
            var ca_Valor2Parameter = ca_Valor2 != null ?
                new ObjectParameter("ca_Valor2", ca_Valor2) :
                new ObjectParameter("ca_Valor2", typeof(string));
    
            var ca_Valor3Parameter = ca_Valor3 != null ?
                new ObjectParameter("ca_Valor3", ca_Valor3) :
                new ObjectParameter("ca_Valor3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Catalogo_Result>("sp_Busqueda_Catalogo", ca_empresaParameter, ca_IdCatalogoParameter, ca_NomCatalogoParameter, ca_CodCatalogoParameter, ca_DescripcionParameter, ca_Valor1Parameter, ca_Valor2Parameter, ca_Valor3Parameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_DetCatalogo_Result> sp_Busqueda_DetCatalogo(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> cd_empresa, Nullable<int> cd_IdCatalogo, string cd_codigo, string cd_valor, string cd_Valor1, string cd_Valor2, string cd_Valor3, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(short));
    
            var cd_IdCatalogoParameter = cd_IdCatalogo.HasValue ?
                new ObjectParameter("cd_IdCatalogo", cd_IdCatalogo) :
                new ObjectParameter("cd_IdCatalogo", typeof(int));
    
            var cd_codigoParameter = cd_codigo != null ?
                new ObjectParameter("cd_codigo", cd_codigo) :
                new ObjectParameter("cd_codigo", typeof(string));
    
            var cd_valorParameter = cd_valor != null ?
                new ObjectParameter("cd_valor", cd_valor) :
                new ObjectParameter("cd_valor", typeof(string));
    
            var cd_Valor1Parameter = cd_Valor1 != null ?
                new ObjectParameter("cd_Valor1", cd_Valor1) :
                new ObjectParameter("cd_Valor1", typeof(string));
    
            var cd_Valor2Parameter = cd_Valor2 != null ?
                new ObjectParameter("cd_Valor2", cd_Valor2) :
                new ObjectParameter("cd_Valor2", typeof(string));
    
            var cd_Valor3Parameter = cd_Valor3 != null ?
                new ObjectParameter("cd_Valor3", cd_Valor3) :
                new ObjectParameter("cd_Valor3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_DetCatalogo_Result>("sp_Busqueda_DetCatalogo", tipoBusquedaParameter, busquedaParameter, cd_empresaParameter, cd_IdCatalogoParameter, cd_codigoParameter, cd_valorParameter, cd_Valor1Parameter, cd_Valor2Parameter, cd_Valor3Parameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Imagen_Result> sp_Busqueda_Imagen(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> im_empresa, Nullable<int> im_CodImagen, string im_NombreImagen, string im_estImagen, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var im_empresaParameter = im_empresa.HasValue ?
                new ObjectParameter("im_empresa", im_empresa) :
                new ObjectParameter("im_empresa", typeof(short));
    
            var im_CodImagenParameter = im_CodImagen.HasValue ?
                new ObjectParameter("im_CodImagen", im_CodImagen) :
                new ObjectParameter("im_CodImagen", typeof(int));
    
            var im_NombreImagenParameter = im_NombreImagen != null ?
                new ObjectParameter("im_NombreImagen", im_NombreImagen) :
                new ObjectParameter("im_NombreImagen", typeof(string));
    
            var im_estImagenParameter = im_estImagen != null ?
                new ObjectParameter("im_estImagen", im_estImagen) :
                new ObjectParameter("im_estImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Imagen_Result>("sp_Busqueda_Imagen", tipoBusquedaParameter, busquedaParameter, im_empresaParameter, im_CodImagenParameter, im_NombreImagenParameter, im_estImagenParameter, error);
        }
    
        public virtual int sp_CorrigeSecuenciales(ObjectParameter error)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CorrigeSecuenciales", error);
        }
    
        public virtual int sp_Obtiene_Secuencial(Nullable<short> sc_empresa, string sc_codtabla, ObjectParameter sec, string sc_usuario, ObjectParameter error)
        {
            var sc_empresaParameter = sc_empresa.HasValue ?
                new ObjectParameter("sc_empresa", sc_empresa) :
                new ObjectParameter("sc_empresa", typeof(short));
    
            var sc_codtablaParameter = sc_codtabla != null ?
                new ObjectParameter("sc_codtabla", sc_codtabla) :
                new ObjectParameter("sc_codtabla", typeof(string));
    
            var sc_usuarioParameter = sc_usuario != null ?
                new ObjectParameter("sc_usuario", sc_usuario) :
                new ObjectParameter("sc_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Obtiene_Secuencial", sc_empresaParameter, sc_codtablaParameter, sec, sc_usuarioParameter, error);
        }
    }
}
