//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCuentaXCobrar
    {
        public short mc_empresa { get; set; }
        public int mc_IdCuentaXCobrar { get; set; }
        public int mc_IdMovCuentaXCobrar { get; set; }
        public int mc_IdSucursal { get; set; }
        public int mc_IdDoc { get; set; }
        public int mc_Cliente { get; set; }
        public System.DateTime mc_FechaMov { get; set; }
        public decimal mc_MontoMov { get; set; }
        public string mc_CreditoDebito { get; set; }
        public string mc_Descripcion { get; set; }
        public string mc_estMovCuentaXCobrar { get; set; }
        public System.DateTime mc_fechaing { get; set; }
        public Nullable<System.DateTime> mc_fechamod { get; set; }
        public string mc_usuarioing { get; set; }
        public string mc_usuariomod { get; set; }
        public string mc_maquinaing { get; set; }
        public string mc_maquinamod { get; set; }
        public int mc_estado { get; set; }
        public byte[] mc_timestamp { get; set; }
    }
}
