//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCuentaXPagar
    {
        public short mp_empresa { get; set; }
        public int mp_IdCuentaXPagar { get; set; }
        public int mp_IdMovCuentaXPagar { get; set; }
        public int mp_IdSucursal { get; set; }
        public int mp_IdDoc { get; set; }
        public int mp_Proveedor { get; set; }
        public System.DateTime mp_FechaMov { get; set; }
        public decimal mp_MontoMov { get; set; }
        public string mp_CreditoDebito { get; set; }
        public string mp_Descripcion { get; set; }
        public string mp_estMovCuentaXPagar { get; set; }
        public System.DateTime mp_fechaing { get; set; }
        public Nullable<System.DateTime> mp_fechamod { get; set; }
        public string mp_usuarioing { get; set; }
        public string mp_usuariomod { get; set; }
        public string mp_maquinaing { get; set; }
        public string mp_maquinamod { get; set; }
        public int mp_estado { get; set; }
        public byte[] mp_timestamp { get; set; }
    }
}
