//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SSS_PERSONASEntities : DbContext
    {
        public SSS_PERSONASEntities()
            : base("name=SSS_PERSONASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Huella> Huella { get; set; }
        public virtual DbSet<NitFactura> NitFactura { get; set; }
        public virtual DbSet<opcion> opcion { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<perfilusuario> perfilusuario { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<vw_UltimosTelefonos> vw_UltimosTelefonos { get; set; }
    
        public virtual int sp_ABC_Cliente(Nullable<short> cl_empresa, string cl_opcion, ObjectParameter cl_cliente, string cl_tipoCliente, string cl_ClasificacionCliente, string cl_tipoident, string cl_identifica, string cl_nit, string cl_nombre1, string cl_nombre2, string cl_nombre3, string cl_apellido1, string cl_apellido2, string cl_apecasada, string cl_genero, Nullable<System.DateTime> cl_fechanac, string cl_ocupacion, string cl_estadocivil, Nullable<int> cl_RecibePublicidad, string cl_usuario, string cl_timestamp, ObjectParameter error)
        {
            var cl_empresaParameter = cl_empresa.HasValue ?
                new ObjectParameter("cl_empresa", cl_empresa) :
                new ObjectParameter("cl_empresa", typeof(short));
    
            var cl_opcionParameter = cl_opcion != null ?
                new ObjectParameter("cl_opcion", cl_opcion) :
                new ObjectParameter("cl_opcion", typeof(string));
    
            var cl_tipoClienteParameter = cl_tipoCliente != null ?
                new ObjectParameter("cl_tipoCliente", cl_tipoCliente) :
                new ObjectParameter("cl_tipoCliente", typeof(string));
    
            var cl_ClasificacionClienteParameter = cl_ClasificacionCliente != null ?
                new ObjectParameter("cl_ClasificacionCliente", cl_ClasificacionCliente) :
                new ObjectParameter("cl_ClasificacionCliente", typeof(string));
    
            var cl_tipoidentParameter = cl_tipoident != null ?
                new ObjectParameter("cl_tipoident", cl_tipoident) :
                new ObjectParameter("cl_tipoident", typeof(string));
    
            var cl_identificaParameter = cl_identifica != null ?
                new ObjectParameter("cl_identifica", cl_identifica) :
                new ObjectParameter("cl_identifica", typeof(string));
    
            var cl_nitParameter = cl_nit != null ?
                new ObjectParameter("cl_nit", cl_nit) :
                new ObjectParameter("cl_nit", typeof(string));
    
            var cl_nombre1Parameter = cl_nombre1 != null ?
                new ObjectParameter("cl_nombre1", cl_nombre1) :
                new ObjectParameter("cl_nombre1", typeof(string));
    
            var cl_nombre2Parameter = cl_nombre2 != null ?
                new ObjectParameter("cl_nombre2", cl_nombre2) :
                new ObjectParameter("cl_nombre2", typeof(string));
    
            var cl_nombre3Parameter = cl_nombre3 != null ?
                new ObjectParameter("cl_nombre3", cl_nombre3) :
                new ObjectParameter("cl_nombre3", typeof(string));
    
            var cl_apellido1Parameter = cl_apellido1 != null ?
                new ObjectParameter("cl_apellido1", cl_apellido1) :
                new ObjectParameter("cl_apellido1", typeof(string));
    
            var cl_apellido2Parameter = cl_apellido2 != null ?
                new ObjectParameter("cl_apellido2", cl_apellido2) :
                new ObjectParameter("cl_apellido2", typeof(string));
    
            var cl_apecasadaParameter = cl_apecasada != null ?
                new ObjectParameter("cl_apecasada", cl_apecasada) :
                new ObjectParameter("cl_apecasada", typeof(string));
    
            var cl_generoParameter = cl_genero != null ?
                new ObjectParameter("cl_genero", cl_genero) :
                new ObjectParameter("cl_genero", typeof(string));
    
            var cl_fechanacParameter = cl_fechanac.HasValue ?
                new ObjectParameter("cl_fechanac", cl_fechanac) :
                new ObjectParameter("cl_fechanac", typeof(System.DateTime));
    
            var cl_ocupacionParameter = cl_ocupacion != null ?
                new ObjectParameter("cl_ocupacion", cl_ocupacion) :
                new ObjectParameter("cl_ocupacion", typeof(string));
    
            var cl_estadocivilParameter = cl_estadocivil != null ?
                new ObjectParameter("cl_estadocivil", cl_estadocivil) :
                new ObjectParameter("cl_estadocivil", typeof(string));
    
            var cl_RecibePublicidadParameter = cl_RecibePublicidad.HasValue ?
                new ObjectParameter("cl_RecibePublicidad", cl_RecibePublicidad) :
                new ObjectParameter("cl_RecibePublicidad", typeof(int));
    
            var cl_usuarioParameter = cl_usuario != null ?
                new ObjectParameter("cl_usuario", cl_usuario) :
                new ObjectParameter("cl_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("cl_timestamp", Convert.FromBase64String(cl_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Cliente", cl_empresaParameter, cl_opcionParameter, cl_cliente, cl_tipoClienteParameter, cl_ClasificacionClienteParameter, cl_tipoidentParameter, cl_identificaParameter, cl_nitParameter, cl_nombre1Parameter, cl_nombre2Parameter, cl_nombre3Parameter, cl_apellido1Parameter, cl_apellido2Parameter, cl_apecasadaParameter, cl_generoParameter, cl_fechanacParameter, cl_ocupacionParameter, cl_estadocivilParameter, cl_RecibePublicidadParameter, cl_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Contacto(Nullable<short> cn_empresa, string cn_opcion, ObjectParameter cn_IdContacto, string cn_tipoAsociado, Nullable<int> cn_asociado, string cn_tipoContacto, string cn_contacto, string cn_contacto2, string cn_usuario, string cn_timestamp, ObjectParameter error)
        {
            var cn_empresaParameter = cn_empresa.HasValue ?
                new ObjectParameter("cn_empresa", cn_empresa) :
                new ObjectParameter("cn_empresa", typeof(short));
    
            var cn_opcionParameter = cn_opcion != null ?
                new ObjectParameter("cn_opcion", cn_opcion) :
                new ObjectParameter("cn_opcion", typeof(string));
    
            var cn_tipoAsociadoParameter = cn_tipoAsociado != null ?
                new ObjectParameter("cn_tipoAsociado", cn_tipoAsociado) :
                new ObjectParameter("cn_tipoAsociado", typeof(string));
    
            var cn_asociadoParameter = cn_asociado.HasValue ?
                new ObjectParameter("cn_asociado", cn_asociado) :
                new ObjectParameter("cn_asociado", typeof(int));
    
            var cn_tipoContactoParameter = cn_tipoContacto != null ?
                new ObjectParameter("cn_tipoContacto", cn_tipoContacto) :
                new ObjectParameter("cn_tipoContacto", typeof(string));
    
            var cn_contactoParameter = cn_contacto != null ?
                new ObjectParameter("cn_contacto", cn_contacto) :
                new ObjectParameter("cn_contacto", typeof(string));
    
            var cn_contacto2Parameter = cn_contacto2 != null ?
                new ObjectParameter("cn_contacto2", cn_contacto2) :
                new ObjectParameter("cn_contacto2", typeof(string));
    
            var cn_usuarioParameter = cn_usuario != null ?
                new ObjectParameter("cn_usuario", cn_usuario) :
                new ObjectParameter("cn_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("cn_timestamp", Convert.FromBase64String(cn_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Contacto", cn_empresaParameter, cn_opcionParameter, cn_IdContacto, cn_tipoAsociadoParameter, cn_asociadoParameter, cn_tipoContactoParameter, cn_contactoParameter, cn_contacto2Parameter, cn_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Direccion(Nullable<short> di_empresa, string di_opcion, ObjectParameter di_IdDireccion, string di_tipoAsociado, Nullable<int> di_asociado, string di_TipoDireccion, string di_Direccion, string di_Direccion2, string di_zona, string di_municipio, string di_departamento, string di_pais, string di_usuario, string di_timestamp, ObjectParameter error)
        {
            var di_empresaParameter = di_empresa.HasValue ?
                new ObjectParameter("di_empresa", di_empresa) :
                new ObjectParameter("di_empresa", typeof(short));
    
            var di_opcionParameter = di_opcion != null ?
                new ObjectParameter("di_opcion", di_opcion) :
                new ObjectParameter("di_opcion", typeof(string));
    
            var di_tipoAsociadoParameter = di_tipoAsociado != null ?
                new ObjectParameter("di_tipoAsociado", di_tipoAsociado) :
                new ObjectParameter("di_tipoAsociado", typeof(string));
    
            var di_asociadoParameter = di_asociado.HasValue ?
                new ObjectParameter("di_asociado", di_asociado) :
                new ObjectParameter("di_asociado", typeof(int));
    
            var di_TipoDireccionParameter = di_TipoDireccion != null ?
                new ObjectParameter("di_TipoDireccion", di_TipoDireccion) :
                new ObjectParameter("di_TipoDireccion", typeof(string));
    
            var di_DireccionParameter = di_Direccion != null ?
                new ObjectParameter("di_Direccion", di_Direccion) :
                new ObjectParameter("di_Direccion", typeof(string));
    
            var di_Direccion2Parameter = di_Direccion2 != null ?
                new ObjectParameter("di_Direccion2", di_Direccion2) :
                new ObjectParameter("di_Direccion2", typeof(string));
    
            var di_zonaParameter = di_zona != null ?
                new ObjectParameter("di_zona", di_zona) :
                new ObjectParameter("di_zona", typeof(string));
    
            var di_municipioParameter = di_municipio != null ?
                new ObjectParameter("di_municipio", di_municipio) :
                new ObjectParameter("di_municipio", typeof(string));
    
            var di_departamentoParameter = di_departamento != null ?
                new ObjectParameter("di_departamento", di_departamento) :
                new ObjectParameter("di_departamento", typeof(string));
    
            var di_paisParameter = di_pais != null ?
                new ObjectParameter("di_pais", di_pais) :
                new ObjectParameter("di_pais", typeof(string));
    
            var di_usuarioParameter = di_usuario != null ?
                new ObjectParameter("di_usuario", di_usuario) :
                new ObjectParameter("di_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("di_timestamp", Convert.FromBase64String(di_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Direccion", di_empresaParameter, di_opcionParameter, di_IdDireccion, di_tipoAsociadoParameter, di_asociadoParameter, di_TipoDireccionParameter, di_DireccionParameter, di_Direccion2Parameter, di_zonaParameter, di_municipioParameter, di_departamentoParameter, di_paisParameter, di_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Foto(Nullable<short> fo_empresa, string fo_opcion, ObjectParameter fo_IdFoto, string fo_tipoAsociado, Nullable<int> fo_asociado, byte[] fo_foto, string fo_usuario, ObjectParameter fo_timestamp, ObjectParameter error)
        {
            var fo_empresaParameter = fo_empresa.HasValue ?
                new ObjectParameter("fo_empresa", fo_empresa) :
                new ObjectParameter("fo_empresa", typeof(short));
    
            var fo_opcionParameter = fo_opcion != null ?
                new ObjectParameter("fo_opcion", fo_opcion) :
                new ObjectParameter("fo_opcion", typeof(string));
    
            var fo_tipoAsociadoParameter = fo_tipoAsociado != null ?
                new ObjectParameter("fo_tipoAsociado", fo_tipoAsociado) :
                new ObjectParameter("fo_tipoAsociado", typeof(string));
    
            var fo_asociadoParameter = fo_asociado.HasValue ?
                new ObjectParameter("fo_asociado", fo_asociado) :
                new ObjectParameter("fo_asociado", typeof(int));
    
            var fo_fotoParameter = fo_foto != null ?
                new ObjectParameter("fo_foto", fo_foto) :
                new ObjectParameter("fo_foto", typeof(byte[]));
    
            var fo_usuarioParameter = fo_usuario != null ?
                new ObjectParameter("fo_usuario", fo_usuario) :
                new ObjectParameter("fo_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Foto", fo_empresaParameter, fo_opcionParameter, fo_IdFoto, fo_tipoAsociadoParameter, fo_asociadoParameter, fo_fotoParameter, fo_usuarioParameter, fo_timestamp, error);
        }
    
        public virtual int sp_ABC_Huella(Nullable<short> hu_empresa, string hu_opcion, ObjectParameter hu_IdHuella, string hu_tipoAsociado, Nullable<int> hu_asociado, byte[] hu_huella, string hu_mano, string hu_dedo, Nullable<int> hu_huella_long, string hu_usuario, ObjectParameter hu_timestamp, ObjectParameter error)
        {
            var hu_empresaParameter = hu_empresa.HasValue ?
                new ObjectParameter("hu_empresa", hu_empresa) :
                new ObjectParameter("hu_empresa", typeof(short));
    
            var hu_opcionParameter = hu_opcion != null ?
                new ObjectParameter("hu_opcion", hu_opcion) :
                new ObjectParameter("hu_opcion", typeof(string));
    
            var hu_tipoAsociadoParameter = hu_tipoAsociado != null ?
                new ObjectParameter("hu_tipoAsociado", hu_tipoAsociado) :
                new ObjectParameter("hu_tipoAsociado", typeof(string));
    
            var hu_asociadoParameter = hu_asociado.HasValue ?
                new ObjectParameter("hu_asociado", hu_asociado) :
                new ObjectParameter("hu_asociado", typeof(int));
    
            var hu_huellaParameter = hu_huella != null ?
                new ObjectParameter("hu_huella", hu_huella) :
                new ObjectParameter("hu_huella", typeof(byte[]));
    
            var hu_manoParameter = hu_mano != null ?
                new ObjectParameter("hu_mano", hu_mano) :
                new ObjectParameter("hu_mano", typeof(string));
    
            var hu_dedoParameter = hu_dedo != null ?
                new ObjectParameter("hu_dedo", hu_dedo) :
                new ObjectParameter("hu_dedo", typeof(string));
    
            var hu_huella_longParameter = hu_huella_long.HasValue ?
                new ObjectParameter("hu_huella_long", hu_huella_long) :
                new ObjectParameter("hu_huella_long", typeof(int));
    
            var hu_usuarioParameter = hu_usuario != null ?
                new ObjectParameter("hu_usuario", hu_usuario) :
                new ObjectParameter("hu_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Huella", hu_empresaParameter, hu_opcionParameter, hu_IdHuella, hu_tipoAsociadoParameter, hu_asociadoParameter, hu_huellaParameter, hu_manoParameter, hu_dedoParameter, hu_huella_longParameter, hu_usuarioParameter, hu_timestamp, error);
        }
    
        public virtual int sp_ABC_NitFactura(Nullable<short> nf_empresa, string nf_opcion, ObjectParameter nf_nit, Nullable<int> nf_IdSucursal, string nf_Nombre, string nf_Direccion, Nullable<int> nf_actCentral, string nf_usuario, string nf_timestamp, ObjectParameter error)
        {
            var nf_empresaParameter = nf_empresa.HasValue ?
                new ObjectParameter("nf_empresa", nf_empresa) :
                new ObjectParameter("nf_empresa", typeof(short));
    
            var nf_opcionParameter = nf_opcion != null ?
                new ObjectParameter("nf_opcion", nf_opcion) :
                new ObjectParameter("nf_opcion", typeof(string));
    
            var nf_IdSucursalParameter = nf_IdSucursal.HasValue ?
                new ObjectParameter("nf_IdSucursal", nf_IdSucursal) :
                new ObjectParameter("nf_IdSucursal", typeof(int));
    
            var nf_NombreParameter = nf_Nombre != null ?
                new ObjectParameter("nf_Nombre", nf_Nombre) :
                new ObjectParameter("nf_Nombre", typeof(string));
    
            var nf_DireccionParameter = nf_Direccion != null ?
                new ObjectParameter("nf_Direccion", nf_Direccion) :
                new ObjectParameter("nf_Direccion", typeof(string));
    
            var nf_actCentralParameter = nf_actCentral.HasValue ?
                new ObjectParameter("nf_actCentral", nf_actCentral) :
                new ObjectParameter("nf_actCentral", typeof(int));
    
            var nf_usuarioParameter = nf_usuario != null ?
                new ObjectParameter("nf_usuario", nf_usuario) :
                new ObjectParameter("nf_usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("nf_timestamp", Convert.FromBase64String(nf_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_NitFactura", nf_empresaParameter, nf_opcionParameter, nf_nit, nf_IdSucursalParameter, nf_NombreParameter, nf_DireccionParameter, nf_actCentralParameter, nf_usuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Opcion(Nullable<short> op_empresa, string op_opcion, ObjectParameter op_codigoOpcion, string op_NombreOpcion, string op_DescOpcion, Nullable<int> op_PadreOpcion, Nullable<bool> op_autenticar, string op_Usuario, string op_timestamp, ObjectParameter error)
        {
            var op_empresaParameter = op_empresa.HasValue ?
                new ObjectParameter("op_empresa", op_empresa) :
                new ObjectParameter("op_empresa", typeof(short));
    
            var op_opcionParameter = op_opcion != null ?
                new ObjectParameter("op_opcion", op_opcion) :
                new ObjectParameter("op_opcion", typeof(string));
    
            var op_NombreOpcionParameter = op_NombreOpcion != null ?
                new ObjectParameter("op_NombreOpcion", op_NombreOpcion) :
                new ObjectParameter("op_NombreOpcion", typeof(string));
    
            var op_DescOpcionParameter = op_DescOpcion != null ?
                new ObjectParameter("op_DescOpcion", op_DescOpcion) :
                new ObjectParameter("op_DescOpcion", typeof(string));
    
            var op_PadreOpcionParameter = op_PadreOpcion.HasValue ?
                new ObjectParameter("op_PadreOpcion", op_PadreOpcion) :
                new ObjectParameter("op_PadreOpcion", typeof(int));
    
            var op_autenticarParameter = op_autenticar.HasValue ?
                new ObjectParameter("op_autenticar", op_autenticar) :
                new ObjectParameter("op_autenticar", typeof(bool));
    
            var op_UsuarioParameter = op_Usuario != null ?
                new ObjectParameter("op_Usuario", op_Usuario) :
                new ObjectParameter("op_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("op_timestamp", Convert.FromBase64String(op_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Opcion", op_empresaParameter, op_opcionParameter, op_codigoOpcion, op_NombreOpcionParameter, op_DescOpcionParameter, op_PadreOpcionParameter, op_autenticarParameter, op_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Perfil(Nullable<short> pf_empresa, string pf_opcion, ObjectParameter pf_codPerfil, string pf_nomPerfil, string pf_DescPerfil, string pf_Usuario, string pf_timestamp, ObjectParameter error)
        {
            var pf_empresaParameter = pf_empresa.HasValue ?
                new ObjectParameter("pf_empresa", pf_empresa) :
                new ObjectParameter("pf_empresa", typeof(short));
    
            var pf_opcionParameter = pf_opcion != null ?
                new ObjectParameter("pf_opcion", pf_opcion) :
                new ObjectParameter("pf_opcion", typeof(string));
    
            var pf_nomPerfilParameter = pf_nomPerfil != null ?
                new ObjectParameter("pf_nomPerfil", pf_nomPerfil) :
                new ObjectParameter("pf_nomPerfil", typeof(string));
    
            var pf_DescPerfilParameter = pf_DescPerfil != null ?
                new ObjectParameter("pf_DescPerfil", pf_DescPerfil) :
                new ObjectParameter("pf_DescPerfil", typeof(string));
    
            var pf_UsuarioParameter = pf_Usuario != null ?
                new ObjectParameter("pf_Usuario", pf_Usuario) :
                new ObjectParameter("pf_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("pf_timestamp", Convert.FromBase64String(pf_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Perfil", pf_empresaParameter, pf_opcionParameter, pf_codPerfil, pf_nomPerfilParameter, pf_DescPerfilParameter, pf_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_PerfilUsuario(Nullable<short> pu_empresa, string pu_opcion, Nullable<int> pu_IdSucursal, ObjectParameter pu_codPerfilUsuario, Nullable<int> pu_codPerfil, Nullable<int> pu_codUsuario, string pu_Usuario, string pu_timestamp, ObjectParameter error)
        {
            var pu_empresaParameter = pu_empresa.HasValue ?
                new ObjectParameter("pu_empresa", pu_empresa) :
                new ObjectParameter("pu_empresa", typeof(short));
    
            var pu_opcionParameter = pu_opcion != null ?
                new ObjectParameter("pu_opcion", pu_opcion) :
                new ObjectParameter("pu_opcion", typeof(string));
    
            var pu_IdSucursalParameter = pu_IdSucursal.HasValue ?
                new ObjectParameter("pu_IdSucursal", pu_IdSucursal) :
                new ObjectParameter("pu_IdSucursal", typeof(int));
    
            var pu_codPerfilParameter = pu_codPerfil.HasValue ?
                new ObjectParameter("pu_codPerfil", pu_codPerfil) :
                new ObjectParameter("pu_codPerfil", typeof(int));
    
            var pu_codUsuarioParameter = pu_codUsuario.HasValue ?
                new ObjectParameter("pu_codUsuario", pu_codUsuario) :
                new ObjectParameter("pu_codUsuario", typeof(int));
    
            var pu_UsuarioParameter = pu_Usuario != null ?
                new ObjectParameter("pu_Usuario", pu_Usuario) :
                new ObjectParameter("pu_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("pu_timestamp", Convert.FromBase64String(pu_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_PerfilUsuario", pu_empresaParameter, pu_opcionParameter, pu_IdSucursalParameter, pu_codPerfilUsuario, pu_codPerfilParameter, pu_codUsuarioParameter, pu_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Permiso(Nullable<short> pe_empresa, string pe_opcion, Nullable<int> pe_IdSucursal, ObjectParameter pe_IdPermiso, Nullable<int> pe_CodPerfil, Nullable<int> pe_codigoOpcion, string pe_Usuario, string pe_timestamp, ObjectParameter error)
        {
            var pe_empresaParameter = pe_empresa.HasValue ?
                new ObjectParameter("pe_empresa", pe_empresa) :
                new ObjectParameter("pe_empresa", typeof(short));
    
            var pe_opcionParameter = pe_opcion != null ?
                new ObjectParameter("pe_opcion", pe_opcion) :
                new ObjectParameter("pe_opcion", typeof(string));
    
            var pe_IdSucursalParameter = pe_IdSucursal.HasValue ?
                new ObjectParameter("pe_IdSucursal", pe_IdSucursal) :
                new ObjectParameter("pe_IdSucursal", typeof(int));
    
            var pe_CodPerfilParameter = pe_CodPerfil.HasValue ?
                new ObjectParameter("pe_CodPerfil", pe_CodPerfil) :
                new ObjectParameter("pe_CodPerfil", typeof(int));
    
            var pe_codigoOpcionParameter = pe_codigoOpcion.HasValue ?
                new ObjectParameter("pe_codigoOpcion", pe_codigoOpcion) :
                new ObjectParameter("pe_codigoOpcion", typeof(int));
    
            var pe_UsuarioParameter = pe_Usuario != null ?
                new ObjectParameter("pe_Usuario", pe_Usuario) :
                new ObjectParameter("pe_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("pe_timestamp", Convert.FromBase64String(pe_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Permiso", pe_empresaParameter, pe_opcionParameter, pe_IdSucursalParameter, pe_IdPermiso, pe_CodPerfilParameter, pe_codigoOpcionParameter, pe_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Proveedor(Nullable<short> pv_empresa, string pv_opcion, ObjectParameter pv_proveedor, string pv_tipoProveedor, string pv_nombre1, string pv_nombre2, string pv_nit, string pv_Usuario, string pv_timestamp, ObjectParameter error)
        {
            var pv_empresaParameter = pv_empresa.HasValue ?
                new ObjectParameter("pv_empresa", pv_empresa) :
                new ObjectParameter("pv_empresa", typeof(short));
    
            var pv_opcionParameter = pv_opcion != null ?
                new ObjectParameter("pv_opcion", pv_opcion) :
                new ObjectParameter("pv_opcion", typeof(string));
    
            var pv_tipoProveedorParameter = pv_tipoProveedor != null ?
                new ObjectParameter("pv_tipoProveedor", pv_tipoProveedor) :
                new ObjectParameter("pv_tipoProveedor", typeof(string));
    
            var pv_nombre1Parameter = pv_nombre1 != null ?
                new ObjectParameter("pv_nombre1", pv_nombre1) :
                new ObjectParameter("pv_nombre1", typeof(string));
    
            var pv_nombre2Parameter = pv_nombre2 != null ?
                new ObjectParameter("pv_nombre2", pv_nombre2) :
                new ObjectParameter("pv_nombre2", typeof(string));
    
            var pv_nitParameter = pv_nit != null ?
                new ObjectParameter("pv_nit", pv_nit) :
                new ObjectParameter("pv_nit", typeof(string));
    
            var pv_UsuarioParameter = pv_Usuario != null ?
                new ObjectParameter("pv_Usuario", pv_Usuario) :
                new ObjectParameter("pv_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("pv_timestamp", Convert.FromBase64String(pv_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Proveedor", pv_empresaParameter, pv_opcionParameter, pv_proveedor, pv_tipoProveedorParameter, pv_nombre1Parameter, pv_nombre2Parameter, pv_nitParameter, pv_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Usuario(Nullable<short> us_empresa, string us_opcion, Nullable<int> us_IdSucursal, ObjectParameter us_codUsuario, string us_usuario, string us_nombre, string us_password, string us_estUsuario, Nullable<int> us_IdEmpleado, string us_usuarioing, Nullable<int> us_resetPass, string us_timestamp, ObjectParameter error)
        {
            var us_empresaParameter = us_empresa.HasValue ?
                new ObjectParameter("us_empresa", us_empresa) :
                new ObjectParameter("us_empresa", typeof(short));
    
            var us_opcionParameter = us_opcion != null ?
                new ObjectParameter("us_opcion", us_opcion) :
                new ObjectParameter("us_opcion", typeof(string));
    
            var us_IdSucursalParameter = us_IdSucursal.HasValue ?
                new ObjectParameter("us_IdSucursal", us_IdSucursal) :
                new ObjectParameter("us_IdSucursal", typeof(int));
    
            var us_usuarioParameter = us_usuario != null ?
                new ObjectParameter("us_usuario", us_usuario) :
                new ObjectParameter("us_usuario", typeof(string));
    
            var us_nombreParameter = us_nombre != null ?
                new ObjectParameter("us_nombre", us_nombre) :
                new ObjectParameter("us_nombre", typeof(string));
    
            var us_passwordParameter = us_password != null ?
                new ObjectParameter("us_password", us_password) :
                new ObjectParameter("us_password", typeof(string));
    
            var us_estUsuarioParameter = us_estUsuario != null ?
                new ObjectParameter("us_estUsuario", us_estUsuario) :
                new ObjectParameter("us_estUsuario", typeof(string));
    
            var us_IdEmpleadoParameter = us_IdEmpleado.HasValue ?
                new ObjectParameter("us_IdEmpleado", us_IdEmpleado) :
                new ObjectParameter("us_IdEmpleado", typeof(int));
    
            var us_usuarioingParameter = us_usuarioing != null ?
                new ObjectParameter("us_usuarioing", us_usuarioing) :
                new ObjectParameter("us_usuarioing", typeof(string));
    
            var us_resetPassParameter = us_resetPass.HasValue ?
                new ObjectParameter("us_resetPass", us_resetPass) :
                new ObjectParameter("us_resetPass", typeof(int));

            ObjectParameter ts = new ObjectParameter("us_timestamp", Convert.FromBase64String(us_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Usuario", us_empresaParameter, us_opcionParameter, us_IdSucursalParameter, us_codUsuario, us_usuarioParameter, us_nombreParameter, us_passwordParameter, us_estUsuarioParameter, us_IdEmpleadoParameter, us_usuarioingParameter, us_resetPassParameter, ts, error);
        }
    
        public virtual int sp_Asigna_PermisosPerfil(Nullable<short> ap_Empresa, Nullable<int> ap_idSucursal, Nullable<int> ap_CodPerfil, Nullable<int> ap_CodigoOpcion, string ap_Usuario, ObjectParameter error)
        {
            var ap_EmpresaParameter = ap_Empresa.HasValue ?
                new ObjectParameter("ap_Empresa", ap_Empresa) :
                new ObjectParameter("ap_Empresa", typeof(short));
    
            var ap_idSucursalParameter = ap_idSucursal.HasValue ?
                new ObjectParameter("ap_idSucursal", ap_idSucursal) :
                new ObjectParameter("ap_idSucursal", typeof(int));
    
            var ap_CodPerfilParameter = ap_CodPerfil.HasValue ?
                new ObjectParameter("ap_CodPerfil", ap_CodPerfil) :
                new ObjectParameter("ap_CodPerfil", typeof(int));
    
            var ap_CodigoOpcionParameter = ap_CodigoOpcion.HasValue ?
                new ObjectParameter("ap_CodigoOpcion", ap_CodigoOpcion) :
                new ObjectParameter("ap_CodigoOpcion", typeof(int));
    
            var ap_UsuarioParameter = ap_Usuario != null ?
                new ObjectParameter("ap_Usuario", ap_Usuario) :
                new ObjectParameter("ap_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Asigna_PermisosPerfil", ap_EmpresaParameter, ap_idSucursalParameter, ap_CodPerfilParameter, ap_CodigoOpcionParameter, ap_UsuarioParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Cliente_Result> sp_Busqueda_Cliente(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> cl_empresa, Nullable<int> cl_cliente, Nullable<int> cl_tipoCliente, Nullable<int> cl_tipoident, string cl_identifica, string cl_nit, string cl_nombre1, string cl_nombre2, string cl_nombre3, string cl_apellido1, string cl_apellido2, string cl_apecasada, Nullable<System.DateTime> cl_fechanac, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var cl_empresaParameter = cl_empresa.HasValue ?
                new ObjectParameter("cl_empresa", cl_empresa) :
                new ObjectParameter("cl_empresa", typeof(short));
    
            var cl_clienteParameter = cl_cliente.HasValue ?
                new ObjectParameter("cl_cliente", cl_cliente) :
                new ObjectParameter("cl_cliente", typeof(int));
    
            var cl_tipoClienteParameter = cl_tipoCliente.HasValue ?
                new ObjectParameter("cl_tipoCliente", cl_tipoCliente) :
                new ObjectParameter("cl_tipoCliente", typeof(int));
    
            var cl_tipoidentParameter = cl_tipoident.HasValue ?
                new ObjectParameter("cl_tipoident", cl_tipoident) :
                new ObjectParameter("cl_tipoident", typeof(int));
    
            var cl_identificaParameter = cl_identifica != null ?
                new ObjectParameter("cl_identifica", cl_identifica) :
                new ObjectParameter("cl_identifica", typeof(string));
    
            var cl_nitParameter = cl_nit != null ?
                new ObjectParameter("cl_nit", cl_nit) :
                new ObjectParameter("cl_nit", typeof(string));
    
            var cl_nombre1Parameter = cl_nombre1 != null ?
                new ObjectParameter("cl_nombre1", cl_nombre1) :
                new ObjectParameter("cl_nombre1", typeof(string));
    
            var cl_nombre2Parameter = cl_nombre2 != null ?
                new ObjectParameter("cl_nombre2", cl_nombre2) :
                new ObjectParameter("cl_nombre2", typeof(string));
    
            var cl_nombre3Parameter = cl_nombre3 != null ?
                new ObjectParameter("cl_nombre3", cl_nombre3) :
                new ObjectParameter("cl_nombre3", typeof(string));
    
            var cl_apellido1Parameter = cl_apellido1 != null ?
                new ObjectParameter("cl_apellido1", cl_apellido1) :
                new ObjectParameter("cl_apellido1", typeof(string));
    
            var cl_apellido2Parameter = cl_apellido2 != null ?
                new ObjectParameter("cl_apellido2", cl_apellido2) :
                new ObjectParameter("cl_apellido2", typeof(string));
    
            var cl_apecasadaParameter = cl_apecasada != null ?
                new ObjectParameter("cl_apecasada", cl_apecasada) :
                new ObjectParameter("cl_apecasada", typeof(string));
    
            var cl_fechanacParameter = cl_fechanac.HasValue ?
                new ObjectParameter("cl_fechanac", cl_fechanac) :
                new ObjectParameter("cl_fechanac", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Cliente_Result>("sp_Busqueda_Cliente", tipoBusquedaParameter, busquedaParameter, cl_empresaParameter, cl_clienteParameter, cl_tipoClienteParameter, cl_tipoidentParameter, cl_identificaParameter, cl_nitParameter, cl_nombre1Parameter, cl_nombre2Parameter, cl_nombre3Parameter, cl_apellido1Parameter, cl_apellido2Parameter, cl_apecasadaParameter, cl_fechanacParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Contacto_Result> sp_Busqueda_Contacto(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> cn_empresa, Nullable<int> cn_idContacto, string cn_tipoasociado, Nullable<int> cn_asociado, string cn_tipoContacto, string cn_Contacto, string cn_Contacto2, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var cn_empresaParameter = cn_empresa.HasValue ?
                new ObjectParameter("cn_empresa", cn_empresa) :
                new ObjectParameter("cn_empresa", typeof(short));
    
            var cn_idContactoParameter = cn_idContacto.HasValue ?
                new ObjectParameter("cn_idContacto", cn_idContacto) :
                new ObjectParameter("cn_idContacto", typeof(int));
    
            var cn_tipoasociadoParameter = cn_tipoasociado != null ?
                new ObjectParameter("cn_tipoasociado", cn_tipoasociado) :
                new ObjectParameter("cn_tipoasociado", typeof(string));
    
            var cn_asociadoParameter = cn_asociado.HasValue ?
                new ObjectParameter("cn_asociado", cn_asociado) :
                new ObjectParameter("cn_asociado", typeof(int));
    
            var cn_tipoContactoParameter = cn_tipoContacto != null ?
                new ObjectParameter("cn_tipoContacto", cn_tipoContacto) :
                new ObjectParameter("cn_tipoContacto", typeof(string));
    
            var cn_ContactoParameter = cn_Contacto != null ?
                new ObjectParameter("cn_Contacto", cn_Contacto) :
                new ObjectParameter("cn_Contacto", typeof(string));
    
            var cn_Contacto2Parameter = cn_Contacto2 != null ?
                new ObjectParameter("cn_Contacto2", cn_Contacto2) :
                new ObjectParameter("cn_Contacto2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Contacto_Result>("sp_Busqueda_Contacto", tipoBusquedaParameter, busquedaParameter, cn_empresaParameter, cn_idContactoParameter, cn_tipoasociadoParameter, cn_asociadoParameter, cn_tipoContactoParameter, cn_ContactoParameter, cn_Contacto2Parameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Direccion_Result> sp_Busqueda_Direccion(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> di_empresa, Nullable<int> di_idDireccion, string di_tipoasociado, Nullable<int> di_asociado, string di_tipoDireccion, string di_Direccion, string di_Direccion2, string di_zona, string di_municipio, string di_departamento, string di_pais, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var di_empresaParameter = di_empresa.HasValue ?
                new ObjectParameter("di_empresa", di_empresa) :
                new ObjectParameter("di_empresa", typeof(short));
    
            var di_idDireccionParameter = di_idDireccion.HasValue ?
                new ObjectParameter("di_idDireccion", di_idDireccion) :
                new ObjectParameter("di_idDireccion", typeof(int));
    
            var di_tipoasociadoParameter = di_tipoasociado != null ?
                new ObjectParameter("di_tipoasociado", di_tipoasociado) :
                new ObjectParameter("di_tipoasociado", typeof(string));
    
            var di_asociadoParameter = di_asociado.HasValue ?
                new ObjectParameter("di_asociado", di_asociado) :
                new ObjectParameter("di_asociado", typeof(int));
    
            var di_tipoDireccionParameter = di_tipoDireccion != null ?
                new ObjectParameter("di_tipoDireccion", di_tipoDireccion) :
                new ObjectParameter("di_tipoDireccion", typeof(string));
    
            var di_DireccionParameter = di_Direccion != null ?
                new ObjectParameter("di_Direccion", di_Direccion) :
                new ObjectParameter("di_Direccion", typeof(string));
    
            var di_Direccion2Parameter = di_Direccion2 != null ?
                new ObjectParameter("di_Direccion2", di_Direccion2) :
                new ObjectParameter("di_Direccion2", typeof(string));
    
            var di_zonaParameter = di_zona != null ?
                new ObjectParameter("di_zona", di_zona) :
                new ObjectParameter("di_zona", typeof(string));
    
            var di_municipioParameter = di_municipio != null ?
                new ObjectParameter("di_municipio", di_municipio) :
                new ObjectParameter("di_municipio", typeof(string));
    
            var di_departamentoParameter = di_departamento != null ?
                new ObjectParameter("di_departamento", di_departamento) :
                new ObjectParameter("di_departamento", typeof(string));
    
            var di_paisParameter = di_pais != null ?
                new ObjectParameter("di_pais", di_pais) :
                new ObjectParameter("di_pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Direccion_Result>("sp_Busqueda_Direccion", tipoBusquedaParameter, busquedaParameter, di_empresaParameter, di_idDireccionParameter, di_tipoasociadoParameter, di_asociadoParameter, di_tipoDireccionParameter, di_DireccionParameter, di_Direccion2Parameter, di_zonaParameter, di_municipioParameter, di_departamentoParameter, di_paisParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Foto_Result> sp_Busqueda_Foto(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> fo_empresa, Nullable<int> fo_IdFoto, string fo_tipoAsociado, Nullable<int> fo_asociado, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var fo_empresaParameter = fo_empresa.HasValue ?
                new ObjectParameter("fo_empresa", fo_empresa) :
                new ObjectParameter("fo_empresa", typeof(short));
    
            var fo_IdFotoParameter = fo_IdFoto.HasValue ?
                new ObjectParameter("fo_IdFoto", fo_IdFoto) :
                new ObjectParameter("fo_IdFoto", typeof(int));
    
            var fo_tipoAsociadoParameter = fo_tipoAsociado != null ?
                new ObjectParameter("fo_tipoAsociado", fo_tipoAsociado) :
                new ObjectParameter("fo_tipoAsociado", typeof(string));
    
            var fo_asociadoParameter = fo_asociado.HasValue ?
                new ObjectParameter("fo_asociado", fo_asociado) :
                new ObjectParameter("fo_asociado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Foto_Result>("sp_Busqueda_Foto", tipoBusquedaParameter, busquedaParameter, fo_empresaParameter, fo_IdFotoParameter, fo_tipoAsociadoParameter, fo_asociadoParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Huella_Result> sp_Busqueda_Huella(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> hu_empresa, Nullable<int> hu_IdHuella, string hu_tipoAsociado, Nullable<int> hu_asociado, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var hu_empresaParameter = hu_empresa.HasValue ?
                new ObjectParameter("hu_empresa", hu_empresa) :
                new ObjectParameter("hu_empresa", typeof(short));
    
            var hu_IdHuellaParameter = hu_IdHuella.HasValue ?
                new ObjectParameter("hu_IdHuella", hu_IdHuella) :
                new ObjectParameter("hu_IdHuella", typeof(int));
    
            var hu_tipoAsociadoParameter = hu_tipoAsociado != null ?
                new ObjectParameter("hu_tipoAsociado", hu_tipoAsociado) :
                new ObjectParameter("hu_tipoAsociado", typeof(string));
    
            var hu_asociadoParameter = hu_asociado.HasValue ?
                new ObjectParameter("hu_asociado", hu_asociado) :
                new ObjectParameter("hu_asociado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Huella_Result>("sp_Busqueda_Huella", tipoBusquedaParameter, busquedaParameter, hu_empresaParameter, hu_IdHuellaParameter, hu_tipoAsociadoParameter, hu_asociadoParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_NitFactura_Result> sp_Busqueda_NitFactura(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> nf_empresa, string nf_nit, Nullable<int> nf_IdSucursal, string nf_Nombre, string nf_Direccion, Nullable<int> nf_actCentral, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var nf_empresaParameter = nf_empresa.HasValue ?
                new ObjectParameter("nf_empresa", nf_empresa) :
                new ObjectParameter("nf_empresa", typeof(short));
    
            var nf_nitParameter = nf_nit != null ?
                new ObjectParameter("nf_nit", nf_nit) :
                new ObjectParameter("nf_nit", typeof(string));
    
            var nf_IdSucursalParameter = nf_IdSucursal.HasValue ?
                new ObjectParameter("nf_IdSucursal", nf_IdSucursal) :
                new ObjectParameter("nf_IdSucursal", typeof(int));
    
            var nf_NombreParameter = nf_Nombre != null ?
                new ObjectParameter("nf_Nombre", nf_Nombre) :
                new ObjectParameter("nf_Nombre", typeof(string));
    
            var nf_DireccionParameter = nf_Direccion != null ?
                new ObjectParameter("nf_Direccion", nf_Direccion) :
                new ObjectParameter("nf_Direccion", typeof(string));
    
            var nf_actCentralParameter = nf_actCentral.HasValue ?
                new ObjectParameter("nf_actCentral", nf_actCentral) :
                new ObjectParameter("nf_actCentral", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_NitFactura_Result>("sp_Busqueda_NitFactura", tipoBusquedaParameter, busquedaParameter, nf_empresaParameter, nf_nitParameter, nf_IdSucursalParameter, nf_NombreParameter, nf_DireccionParameter, nf_actCentralParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Opcion_Result> sp_Busqueda_Opcion(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> op_Empresa, Nullable<int> op_CodigoOpcion, string op_NombreOpcion, string op_DescOpcion, Nullable<int> op_PadreOpcion, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var op_EmpresaParameter = op_Empresa.HasValue ?
                new ObjectParameter("op_Empresa", op_Empresa) :
                new ObjectParameter("op_Empresa", typeof(short));
    
            var op_CodigoOpcionParameter = op_CodigoOpcion.HasValue ?
                new ObjectParameter("op_CodigoOpcion", op_CodigoOpcion) :
                new ObjectParameter("op_CodigoOpcion", typeof(int));
    
            var op_NombreOpcionParameter = op_NombreOpcion != null ?
                new ObjectParameter("op_NombreOpcion", op_NombreOpcion) :
                new ObjectParameter("op_NombreOpcion", typeof(string));
    
            var op_DescOpcionParameter = op_DescOpcion != null ?
                new ObjectParameter("op_DescOpcion", op_DescOpcion) :
                new ObjectParameter("op_DescOpcion", typeof(string));
    
            var op_PadreOpcionParameter = op_PadreOpcion.HasValue ?
                new ObjectParameter("op_PadreOpcion", op_PadreOpcion) :
                new ObjectParameter("op_PadreOpcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Opcion_Result>("sp_Busqueda_Opcion", tipoBusquedaParameter, busquedaParameter, op_EmpresaParameter, op_CodigoOpcionParameter, op_NombreOpcionParameter, op_DescOpcionParameter, op_PadreOpcionParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Perfil_Result> sp_Busqueda_Perfil(Nullable<int> tipoBusqueda, string busqueda, Nullable<int> pf_empresa, Nullable<int> pf_codPerfil, string pf_nomPerfil, string pf_descPerfil, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var pf_empresaParameter = pf_empresa.HasValue ?
                new ObjectParameter("pf_empresa", pf_empresa) :
                new ObjectParameter("pf_empresa", typeof(int));
    
            var pf_codPerfilParameter = pf_codPerfil.HasValue ?
                new ObjectParameter("pf_codPerfil", pf_codPerfil) :
                new ObjectParameter("pf_codPerfil", typeof(int));
    
            var pf_nomPerfilParameter = pf_nomPerfil != null ?
                new ObjectParameter("pf_nomPerfil", pf_nomPerfil) :
                new ObjectParameter("pf_nomPerfil", typeof(string));
    
            var pf_descPerfilParameter = pf_descPerfil != null ?
                new ObjectParameter("pf_descPerfil", pf_descPerfil) :
                new ObjectParameter("pf_descPerfil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Perfil_Result>("sp_Busqueda_Perfil", tipoBusquedaParameter, busquedaParameter, pf_empresaParameter, pf_codPerfilParameter, pf_nomPerfilParameter, pf_descPerfilParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_PerfilUsuario_Result> sp_Busqueda_PerfilUsuario(Nullable<int> tipoBusqueda, string busqueda, Nullable<int> pu_empresa, Nullable<int> pu_IdSucursal, Nullable<int> pu_codPerfil, Nullable<int> pu_codUsuario, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var pu_empresaParameter = pu_empresa.HasValue ?
                new ObjectParameter("pu_empresa", pu_empresa) :
                new ObjectParameter("pu_empresa", typeof(int));
    
            var pu_IdSucursalParameter = pu_IdSucursal.HasValue ?
                new ObjectParameter("pu_IdSucursal", pu_IdSucursal) :
                new ObjectParameter("pu_IdSucursal", typeof(int));
    
            var pu_codPerfilParameter = pu_codPerfil.HasValue ?
                new ObjectParameter("pu_codPerfil", pu_codPerfil) :
                new ObjectParameter("pu_codPerfil", typeof(int));
    
            var pu_codUsuarioParameter = pu_codUsuario.HasValue ?
                new ObjectParameter("pu_codUsuario", pu_codUsuario) :
                new ObjectParameter("pu_codUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_PerfilUsuario_Result>("sp_Busqueda_PerfilUsuario", tipoBusquedaParameter, busquedaParameter, pu_empresaParameter, pu_IdSucursalParameter, pu_codPerfilParameter, pu_codUsuarioParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Permiso_Result> sp_Busqueda_Permiso(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> pe_Empresa, Nullable<int> pe_IdSucursal, Nullable<int> pe_CodPerfil, Nullable<int> pe_CodigoOpcion, Nullable<int> pe_PadreOpcion, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var pe_EmpresaParameter = pe_Empresa.HasValue ?
                new ObjectParameter("pe_Empresa", pe_Empresa) :
                new ObjectParameter("pe_Empresa", typeof(short));
    
            var pe_IdSucursalParameter = pe_IdSucursal.HasValue ?
                new ObjectParameter("pe_IdSucursal", pe_IdSucursal) :
                new ObjectParameter("pe_IdSucursal", typeof(int));
    
            var pe_CodPerfilParameter = pe_CodPerfil.HasValue ?
                new ObjectParameter("pe_CodPerfil", pe_CodPerfil) :
                new ObjectParameter("pe_CodPerfil", typeof(int));
    
            var pe_CodigoOpcionParameter = pe_CodigoOpcion.HasValue ?
                new ObjectParameter("pe_CodigoOpcion", pe_CodigoOpcion) :
                new ObjectParameter("pe_CodigoOpcion", typeof(int));
    
            var pe_PadreOpcionParameter = pe_PadreOpcion.HasValue ?
                new ObjectParameter("pe_PadreOpcion", pe_PadreOpcion) :
                new ObjectParameter("pe_PadreOpcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Permiso_Result>("sp_Busqueda_Permiso", tipoBusquedaParameter, busquedaParameter, pe_EmpresaParameter, pe_IdSucursalParameter, pe_CodPerfilParameter, pe_CodigoOpcionParameter, pe_PadreOpcionParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_PermisosUsuario_Result> sp_Busqueda_PermisosUsuario(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> us_Empresa, Nullable<int> us_IdSucursal, Nullable<int> us_CodUsuario, Nullable<int> us_CodPerfil, Nullable<int> us_CodigoOpcion, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var us_EmpresaParameter = us_Empresa.HasValue ?
                new ObjectParameter("us_Empresa", us_Empresa) :
                new ObjectParameter("us_Empresa", typeof(short));
    
            var us_IdSucursalParameter = us_IdSucursal.HasValue ?
                new ObjectParameter("us_IdSucursal", us_IdSucursal) :
                new ObjectParameter("us_IdSucursal", typeof(int));
    
            var us_CodUsuarioParameter = us_CodUsuario.HasValue ?
                new ObjectParameter("us_CodUsuario", us_CodUsuario) :
                new ObjectParameter("us_CodUsuario", typeof(int));
    
            var us_CodPerfilParameter = us_CodPerfil.HasValue ?
                new ObjectParameter("us_CodPerfil", us_CodPerfil) :
                new ObjectParameter("us_CodPerfil", typeof(int));
    
            var us_CodigoOpcionParameter = us_CodigoOpcion.HasValue ?
                new ObjectParameter("us_CodigoOpcion", us_CodigoOpcion) :
                new ObjectParameter("us_CodigoOpcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_PermisosUsuario_Result>("sp_Busqueda_PermisosUsuario", tipoBusquedaParameter, busquedaParameter, us_EmpresaParameter, us_IdSucursalParameter, us_CodUsuarioParameter, us_CodPerfilParameter, us_CodigoOpcionParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Proveedor_Result> sp_Busqueda_Proveedor(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> pv_empresa, Nullable<int> pv_proveedor, Nullable<int> pv_tipoProveedor, string pv_nombre1, string pv_nombre2, string pv_nit, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var pv_empresaParameter = pv_empresa.HasValue ?
                new ObjectParameter("pv_empresa", pv_empresa) :
                new ObjectParameter("pv_empresa", typeof(short));
    
            var pv_proveedorParameter = pv_proveedor.HasValue ?
                new ObjectParameter("pv_proveedor", pv_proveedor) :
                new ObjectParameter("pv_proveedor", typeof(int));
    
            var pv_tipoProveedorParameter = pv_tipoProveedor.HasValue ?
                new ObjectParameter("pv_tipoProveedor", pv_tipoProveedor) :
                new ObjectParameter("pv_tipoProveedor", typeof(int));
    
            var pv_nombre1Parameter = pv_nombre1 != null ?
                new ObjectParameter("pv_nombre1", pv_nombre1) :
                new ObjectParameter("pv_nombre1", typeof(string));
    
            var pv_nombre2Parameter = pv_nombre2 != null ?
                new ObjectParameter("pv_nombre2", pv_nombre2) :
                new ObjectParameter("pv_nombre2", typeof(string));
    
            var pv_nitParameter = pv_nit != null ?
                new ObjectParameter("pv_nit", pv_nit) :
                new ObjectParameter("pv_nit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Proveedor_Result>("sp_Busqueda_Proveedor", tipoBusquedaParameter, busquedaParameter, pv_empresaParameter, pv_proveedorParameter, pv_tipoProveedorParameter, pv_nombre1Parameter, pv_nombre2Parameter, pv_nitParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Usuario_Result> sp_Busqueda_Usuario(Nullable<int> tipoBusqueda, string busqueda, Nullable<int> us_empresa, Nullable<int> us_IdSucursal, Nullable<int> us_codUsuario, string us_usuario, string us_nombre, string us_estUsuario, Nullable<int> us_IdEmpleado, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var us_empresaParameter = us_empresa.HasValue ?
                new ObjectParameter("us_empresa", us_empresa) :
                new ObjectParameter("us_empresa", typeof(int));
    
            var us_IdSucursalParameter = us_IdSucursal.HasValue ?
                new ObjectParameter("us_IdSucursal", us_IdSucursal) :
                new ObjectParameter("us_IdSucursal", typeof(int));
    
            var us_codUsuarioParameter = us_codUsuario.HasValue ?
                new ObjectParameter("us_codUsuario", us_codUsuario) :
                new ObjectParameter("us_codUsuario", typeof(int));
    
            var us_usuarioParameter = us_usuario != null ?
                new ObjectParameter("us_usuario", us_usuario) :
                new ObjectParameter("us_usuario", typeof(string));
    
            var us_nombreParameter = us_nombre != null ?
                new ObjectParameter("us_nombre", us_nombre) :
                new ObjectParameter("us_nombre", typeof(string));
    
            var us_estUsuarioParameter = us_estUsuario != null ?
                new ObjectParameter("us_estUsuario", us_estUsuario) :
                new ObjectParameter("us_estUsuario", typeof(string));
    
            var us_IdEmpleadoParameter = us_IdEmpleado.HasValue ?
                new ObjectParameter("us_IdEmpleado", us_IdEmpleado) :
                new ObjectParameter("us_IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Usuario_Result>("sp_Busqueda_Usuario", tipoBusquedaParameter, busquedaParameter, us_empresaParameter, us_IdSucursalParameter, us_codUsuarioParameter, us_usuarioParameter, us_nombreParameter, us_estUsuarioParameter, us_IdEmpleadoParameter, error);
        }
    
        public virtual ObjectResult<sp_CargaPermisos_Result> sp_CargaPermisos(Nullable<short> cp_empresa, Nullable<int> cp_codUsuario, ObjectParameter error)
        {
            var cp_empresaParameter = cp_empresa.HasValue ?
                new ObjectParameter("cp_empresa", cp_empresa) :
                new ObjectParameter("cp_empresa", typeof(short));
    
            var cp_codUsuarioParameter = cp_codUsuario.HasValue ?
                new ObjectParameter("cp_codUsuario", cp_codUsuario) :
                new ObjectParameter("cp_codUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CargaPermisos_Result>("sp_CargaPermisos", cp_empresaParameter, cp_codUsuarioParameter, error);
        }
    
        public virtual ObjectResult<sp_Login_Result> sp_Login(Nullable<short> lg_empresa, string lg_usuario, string lg_password,  ObjectParameter error)
        {
            var lg_empresaParameter = lg_empresa.HasValue ?
                new ObjectParameter("lg_empresa", lg_empresa) :
                new ObjectParameter("lg_empresa", typeof(short));
    
            var lg_usuarioParameter = lg_usuario != null ?
                new ObjectParameter("lg_usuario", lg_usuario) :
                new ObjectParameter("lg_usuario", typeof(string));
    
            var lg_passwordParameter = lg_password != null ?
                new ObjectParameter("lg_password", lg_password) :
                new ObjectParameter("lg_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Result>("sp_Login", lg_empresaParameter, lg_usuarioParameter, lg_passwordParameter, error);
        }
    
        public virtual int sp_RegistrosNuevos(Nullable<short> cl_empresa, ObjectParameter error)
        {
            var cl_empresaParameter = cl_empresa.HasValue ?
                new ObjectParameter("cl_empresa", cl_empresa) :
                new ObjectParameter("cl_empresa", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrosNuevos", cl_empresaParameter, error);
        }
    
        public virtual ObjectResult<sp_ValidaCumpleanios_Result> sp_ValidaCumpleanios(Nullable<short> cl_empresa, Nullable<int> cl_cliente, ObjectParameter error)
        {
            var cl_empresaParameter = cl_empresa.HasValue ?
                new ObjectParameter("cl_empresa", cl_empresa) :
                new ObjectParameter("cl_empresa", typeof(short));
    
            var cl_clienteParameter = cl_cliente.HasValue ?
                new ObjectParameter("cl_cliente", cl_cliente) :
                new ObjectParameter("cl_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ValidaCumpleanios_Result>("sp_ValidaCumpleanios", cl_empresaParameter, cl_clienteParameter, error);
        }
    }
}
