//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SSS_PLANILLAEntities : DbContext
    {
        public SSS_PLANILLAEntities()
            : base("name=SSS_PLANILLAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<HorarioEmpleado> HorarioEmpleadoes { get; set; }
    
        public virtual int sp_ABC_Empleado(Nullable<short> em_empresa, string em_opcion, ObjectParameter em_IdEmpleado, string em_tipoEmpleado, string em_tipoIdentifica, string em_Identifica, string em_Nit, string em_Nombre1, string em_Nombre2, string em_Nombre3, string em_Apellido1, string em_Apellido2, string em_ApeCasada, string em_Alias, string em_genero, Nullable<System.DateTime> em_FechaNac, string em_ocupacion, string em_estadoCivil, string em_estEmpleado, Nullable<System.DateTime> em_FechaIngreso, Nullable<System.DateTime> em_FechaSalida, Nullable<decimal> em_SueldoBase, Nullable<decimal> em_Bonificacion, string em_Usuario, string em_timestamp, ObjectParameter error)
        {
            var em_empresaParameter = em_empresa.HasValue ?
                new ObjectParameter("em_empresa", em_empresa) :
                new ObjectParameter("em_empresa", typeof(short));
    
            var em_opcionParameter = em_opcion != null ?
                new ObjectParameter("em_opcion", em_opcion) :
                new ObjectParameter("em_opcion", typeof(string));
    
            var em_tipoEmpleadoParameter = em_tipoEmpleado != null ?
                new ObjectParameter("em_tipoEmpleado", em_tipoEmpleado) :
                new ObjectParameter("em_tipoEmpleado", typeof(string));
    
            var em_tipoIdentificaParameter = em_tipoIdentifica != null ?
                new ObjectParameter("em_tipoIdentifica", em_tipoIdentifica) :
                new ObjectParameter("em_tipoIdentifica", typeof(string));
    
            var em_IdentificaParameter = em_Identifica != null ?
                new ObjectParameter("em_Identifica", em_Identifica) :
                new ObjectParameter("em_Identifica", typeof(string));
    
            var em_NitParameter = em_Nit != null ?
                new ObjectParameter("em_Nit", em_Nit) :
                new ObjectParameter("em_Nit", typeof(string));
    
            var em_Nombre1Parameter = em_Nombre1 != null ?
                new ObjectParameter("em_Nombre1", em_Nombre1) :
                new ObjectParameter("em_Nombre1", typeof(string));
    
            var em_Nombre2Parameter = em_Nombre2 != null ?
                new ObjectParameter("em_Nombre2", em_Nombre2) :
                new ObjectParameter("em_Nombre2", typeof(string));
    
            var em_Nombre3Parameter = em_Nombre3 != null ?
                new ObjectParameter("em_Nombre3", em_Nombre3) :
                new ObjectParameter("em_Nombre3", typeof(string));
    
            var em_Apellido1Parameter = em_Apellido1 != null ?
                new ObjectParameter("em_Apellido1", em_Apellido1) :
                new ObjectParameter("em_Apellido1", typeof(string));
    
            var em_Apellido2Parameter = em_Apellido2 != null ?
                new ObjectParameter("em_Apellido2", em_Apellido2) :
                new ObjectParameter("em_Apellido2", typeof(string));
    
            var em_ApeCasadaParameter = em_ApeCasada != null ?
                new ObjectParameter("em_ApeCasada", em_ApeCasada) :
                new ObjectParameter("em_ApeCasada", typeof(string));
    
            var em_AliasParameter = em_Alias != null ?
                new ObjectParameter("em_Alias", em_Alias) :
                new ObjectParameter("em_Alias", typeof(string));
    
            var em_generoParameter = em_genero != null ?
                new ObjectParameter("em_genero", em_genero) :
                new ObjectParameter("em_genero", typeof(string));
    
            var em_FechaNacParameter = em_FechaNac.HasValue ?
                new ObjectParameter("em_FechaNac", em_FechaNac) :
                new ObjectParameter("em_FechaNac", typeof(System.DateTime));
    
            var em_ocupacionParameter = em_ocupacion != null ?
                new ObjectParameter("em_ocupacion", em_ocupacion) :
                new ObjectParameter("em_ocupacion", typeof(string));
    
            var em_estadoCivilParameter = em_estadoCivil != null ?
                new ObjectParameter("em_estadoCivil", em_estadoCivil) :
                new ObjectParameter("em_estadoCivil", typeof(string));
    
            var em_estEmpleadoParameter = em_estEmpleado != null ?
                new ObjectParameter("em_estEmpleado", em_estEmpleado) :
                new ObjectParameter("em_estEmpleado", typeof(string));
    
            var em_FechaIngresoParameter = em_FechaIngreso.HasValue ?
                new ObjectParameter("em_FechaIngreso", em_FechaIngreso) :
                new ObjectParameter("em_FechaIngreso", typeof(System.DateTime));
    
            var em_FechaSalidaParameter = em_FechaSalida.HasValue ?
                new ObjectParameter("em_FechaSalida", em_FechaSalida) :
                new ObjectParameter("em_FechaSalida", typeof(System.DateTime));
    
            var em_SueldoBaseParameter = em_SueldoBase.HasValue ?
                new ObjectParameter("em_SueldoBase", em_SueldoBase) :
                new ObjectParameter("em_SueldoBase", typeof(decimal));
    
            var em_BonificacionParameter = em_Bonificacion.HasValue ?
                new ObjectParameter("em_Bonificacion", em_Bonificacion) :
                new ObjectParameter("em_Bonificacion", typeof(decimal));
    
            var em_UsuarioParameter = em_Usuario != null ?
                new ObjectParameter("em_Usuario", em_Usuario) :
                new ObjectParameter("em_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("em_timestamp", Convert.FromBase64String(em_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Empleado", em_empresaParameter, em_opcionParameter, em_IdEmpleado, em_tipoEmpleadoParameter, em_tipoIdentificaParameter, em_IdentificaParameter, em_NitParameter, em_Nombre1Parameter, em_Nombre2Parameter, em_Nombre3Parameter, em_Apellido1Parameter, em_Apellido2Parameter, em_ApeCasadaParameter, em_AliasParameter, em_generoParameter, em_FechaNacParameter, em_ocupacionParameter, em_estadoCivilParameter, em_estEmpleadoParameter, em_FechaIngresoParameter, em_FechaSalidaParameter, em_SueldoBaseParameter, em_BonificacionParameter, em_UsuarioParameter, ts, error);
        }
    
        public virtual int sp_ABC_Horario(Nullable<short> ho_empresa, string ho_opcion, ObjectParameter ho_IdHorario, Nullable<int> ho_diaSemana, string ho_Nombre, string ho_Descripcion, string ho_HoraEntrada, string ho_HoraSalida, string ho_HoraSalidaAlmuerzo, string ho_HoraEntradaAlmuerzo, string ho_Usuario, string ho_timestamp, ObjectParameter error)
        {
            var ho_empresaParameter = ho_empresa.HasValue ?
                new ObjectParameter("ho_empresa", ho_empresa) :
                new ObjectParameter("ho_empresa", typeof(short));
    
            var ho_opcionParameter = ho_opcion != null ?
                new ObjectParameter("ho_opcion", ho_opcion) :
                new ObjectParameter("ho_opcion", typeof(string));
    
            var ho_diaSemanaParameter = ho_diaSemana.HasValue ?
                new ObjectParameter("ho_diaSemana", ho_diaSemana) :
                new ObjectParameter("ho_diaSemana", typeof(int));
    
            var ho_NombreParameter = ho_Nombre != null ?
                new ObjectParameter("ho_Nombre", ho_Nombre) :
                new ObjectParameter("ho_Nombre", typeof(string));
    
            var ho_DescripcionParameter = ho_Descripcion != null ?
                new ObjectParameter("ho_Descripcion", ho_Descripcion) :
                new ObjectParameter("ho_Descripcion", typeof(string));
    
            var ho_HoraEntradaParameter = ho_HoraEntrada != null ?
                new ObjectParameter("ho_HoraEntrada", ho_HoraEntrada) :
                new ObjectParameter("ho_HoraEntrada", typeof(string));
    
            var ho_HoraSalidaParameter = ho_HoraSalida != null ?
                new ObjectParameter("ho_HoraSalida", ho_HoraSalida) :
                new ObjectParameter("ho_HoraSalida", typeof(string));
    
            var ho_HoraSalidaAlmuerzoParameter = ho_HoraSalidaAlmuerzo != null ?
                new ObjectParameter("ho_HoraSalidaAlmuerzo", ho_HoraSalidaAlmuerzo) :
                new ObjectParameter("ho_HoraSalidaAlmuerzo", typeof(string));
    
            var ho_HoraEntradaAlmuerzoParameter = ho_HoraEntradaAlmuerzo != null ?
                new ObjectParameter("ho_HoraEntradaAlmuerzo", ho_HoraEntradaAlmuerzo) :
                new ObjectParameter("ho_HoraEntradaAlmuerzo", typeof(string));
    
            var ho_UsuarioParameter = ho_Usuario != null ?
                new ObjectParameter("ho_Usuario", ho_Usuario) :
                new ObjectParameter("ho_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("ho_timestamp", Convert.FromBase64String(ho_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_Horario", ho_empresaParameter, ho_opcionParameter, ho_IdHorario, ho_diaSemanaParameter, ho_NombreParameter, ho_DescripcionParameter, ho_HoraEntradaParameter, ho_HoraSalidaParameter, ho_HoraSalidaAlmuerzoParameter, ho_HoraEntradaAlmuerzoParameter, ho_UsuarioParameter, ts , error);
        }
    
        public virtual int sp_ABC_HorarioEmpleado(Nullable<short> he_empresa, string he_opcion, Nullable<int> he_IdHorario, Nullable<int> he_diaSemana, Nullable<int> he_IdEmpleado, string he_Usuario, string he_timestamp, ObjectParameter error)
        {
            var he_empresaParameter = he_empresa.HasValue ?
                new ObjectParameter("he_empresa", he_empresa) :
                new ObjectParameter("he_empresa", typeof(short));
    
            var he_opcionParameter = he_opcion != null ?
                new ObjectParameter("he_opcion", he_opcion) :
                new ObjectParameter("he_opcion", typeof(string));
    
            var he_IdHorarioParameter = he_IdHorario.HasValue ?
                new ObjectParameter("he_IdHorario", he_IdHorario) :
                new ObjectParameter("he_IdHorario", typeof(int));
    
            var he_diaSemanaParameter = he_diaSemana.HasValue ?
                new ObjectParameter("he_diaSemana", he_diaSemana) :
                new ObjectParameter("he_diaSemana", typeof(int));
    
            var he_IdEmpleadoParameter = he_IdEmpleado.HasValue ?
                new ObjectParameter("he_IdEmpleado", he_IdEmpleado) :
                new ObjectParameter("he_IdEmpleado", typeof(int));
    
            var he_UsuarioParameter = he_Usuario != null ?
                new ObjectParameter("he_Usuario", he_Usuario) :
                new ObjectParameter("he_Usuario", typeof(string));

            ObjectParameter ts = new ObjectParameter("he_timestamp", Convert.FromBase64String(he_timestamp));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ABC_HorarioEmpleado", he_empresaParameter, he_opcionParameter, he_IdHorarioParameter, he_diaSemanaParameter, he_IdEmpleadoParameter, he_UsuarioParameter, ts, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Empleado_Result> sp_Busqueda_Empleado(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> em_empresa, Nullable<int> em_IdEmpleado, string em_tipoEmpleado, string em_tipoIdentifica, string em_Identifica, string em_Nit, string em_Nombre1, string em_Nombre2, string em_Nombre3, string em_Apellido1, string em_Apellido2, string em_ApeCasada, string em_Alias, string em_genero, Nullable<System.DateTime> em_FechaNac, string em_ocupacion, string em_estadoCivil, string em_estEmpleado, Nullable<System.DateTime> em_FechaIngreso, Nullable<System.DateTime> em_FechaSalida, Nullable<decimal> em_SueldoBase, Nullable<decimal> em_Bonificacion, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var em_empresaParameter = em_empresa.HasValue ?
                new ObjectParameter("em_empresa", em_empresa) :
                new ObjectParameter("em_empresa", typeof(short));
    
            var em_IdEmpleadoParameter = em_IdEmpleado.HasValue ?
                new ObjectParameter("em_IdEmpleado", em_IdEmpleado) :
                new ObjectParameter("em_IdEmpleado", typeof(int));
    
            var em_tipoEmpleadoParameter = em_tipoEmpleado != null ?
                new ObjectParameter("em_tipoEmpleado", em_tipoEmpleado) :
                new ObjectParameter("em_tipoEmpleado", typeof(string));
    
            var em_tipoIdentificaParameter = em_tipoIdentifica != null ?
                new ObjectParameter("em_tipoIdentifica", em_tipoIdentifica) :
                new ObjectParameter("em_tipoIdentifica", typeof(string));
    
            var em_IdentificaParameter = em_Identifica != null ?
                new ObjectParameter("em_Identifica", em_Identifica) :
                new ObjectParameter("em_Identifica", typeof(string));
    
            var em_NitParameter = em_Nit != null ?
                new ObjectParameter("em_Nit", em_Nit) :
                new ObjectParameter("em_Nit", typeof(string));
    
            var em_Nombre1Parameter = em_Nombre1 != null ?
                new ObjectParameter("em_Nombre1", em_Nombre1) :
                new ObjectParameter("em_Nombre1", typeof(string));
    
            var em_Nombre2Parameter = em_Nombre2 != null ?
                new ObjectParameter("em_Nombre2", em_Nombre2) :
                new ObjectParameter("em_Nombre2", typeof(string));
    
            var em_Nombre3Parameter = em_Nombre3 != null ?
                new ObjectParameter("em_Nombre3", em_Nombre3) :
                new ObjectParameter("em_Nombre3", typeof(string));
    
            var em_Apellido1Parameter = em_Apellido1 != null ?
                new ObjectParameter("em_Apellido1", em_Apellido1) :
                new ObjectParameter("em_Apellido1", typeof(string));
    
            var em_Apellido2Parameter = em_Apellido2 != null ?
                new ObjectParameter("em_Apellido2", em_Apellido2) :
                new ObjectParameter("em_Apellido2", typeof(string));
    
            var em_ApeCasadaParameter = em_ApeCasada != null ?
                new ObjectParameter("em_ApeCasada", em_ApeCasada) :
                new ObjectParameter("em_ApeCasada", typeof(string));
    
            var em_AliasParameter = em_Alias != null ?
                new ObjectParameter("em_Alias", em_Alias) :
                new ObjectParameter("em_Alias", typeof(string));
    
            var em_generoParameter = em_genero != null ?
                new ObjectParameter("em_genero", em_genero) :
                new ObjectParameter("em_genero", typeof(string));
    
            var em_FechaNacParameter = em_FechaNac.HasValue ?
                new ObjectParameter("em_FechaNac", em_FechaNac) :
                new ObjectParameter("em_FechaNac", typeof(System.DateTime));
    
            var em_ocupacionParameter = em_ocupacion != null ?
                new ObjectParameter("em_ocupacion", em_ocupacion) :
                new ObjectParameter("em_ocupacion", typeof(string));
    
            var em_estadoCivilParameter = em_estadoCivil != null ?
                new ObjectParameter("em_estadoCivil", em_estadoCivil) :
                new ObjectParameter("em_estadoCivil", typeof(string));
    
            var em_estEmpleadoParameter = em_estEmpleado != null ?
                new ObjectParameter("em_estEmpleado", em_estEmpleado) :
                new ObjectParameter("em_estEmpleado", typeof(string));
    
            var em_FechaIngresoParameter = em_FechaIngreso.HasValue ?
                new ObjectParameter("em_FechaIngreso", em_FechaIngreso) :
                new ObjectParameter("em_FechaIngreso", typeof(System.DateTime));
    
            var em_FechaSalidaParameter = em_FechaSalida.HasValue ?
                new ObjectParameter("em_FechaSalida", em_FechaSalida) :
                new ObjectParameter("em_FechaSalida", typeof(System.DateTime));
    
            var em_SueldoBaseParameter = em_SueldoBase.HasValue ?
                new ObjectParameter("em_SueldoBase", em_SueldoBase) :
                new ObjectParameter("em_SueldoBase", typeof(decimal));
    
            var em_BonificacionParameter = em_Bonificacion.HasValue ?
                new ObjectParameter("em_Bonificacion", em_Bonificacion) :
                new ObjectParameter("em_Bonificacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Empleado_Result>("sp_Busqueda_Empleado", tipoBusquedaParameter, busquedaParameter, em_empresaParameter, em_IdEmpleadoParameter, em_tipoEmpleadoParameter, em_tipoIdentificaParameter, em_IdentificaParameter, em_NitParameter, em_Nombre1Parameter, em_Nombre2Parameter, em_Nombre3Parameter, em_Apellido1Parameter, em_Apellido2Parameter, em_ApeCasadaParameter, em_AliasParameter, em_generoParameter, em_FechaNacParameter, em_ocupacionParameter, em_estadoCivilParameter, em_estEmpleadoParameter, em_FechaIngresoParameter, em_FechaSalidaParameter, em_SueldoBaseParameter, em_BonificacionParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_Horario_Result> sp_Busqueda_Horario(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> ho_empresa, Nullable<int> ho_IdHorario, Nullable<int> ho_diaSemana, string ho_Nombre, string ho_Descripcion, string ho_HoraEntrada, string ho_HoraSalida, string ho_HoraSalidaAlmuerzo, string ho_HoraEntradaAlmuerzo, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var ho_empresaParameter = ho_empresa.HasValue ?
                new ObjectParameter("ho_empresa", ho_empresa) :
                new ObjectParameter("ho_empresa", typeof(short));
    
            var ho_IdHorarioParameter = ho_IdHorario.HasValue ?
                new ObjectParameter("ho_IdHorario", ho_IdHorario) :
                new ObjectParameter("ho_IdHorario", typeof(int));
    
            var ho_diaSemanaParameter = ho_diaSemana.HasValue ?
                new ObjectParameter("ho_diaSemana", ho_diaSemana) :
                new ObjectParameter("ho_diaSemana", typeof(int));
    
            var ho_NombreParameter = ho_Nombre != null ?
                new ObjectParameter("ho_Nombre", ho_Nombre) :
                new ObjectParameter("ho_Nombre", typeof(string));
    
            var ho_DescripcionParameter = ho_Descripcion != null ?
                new ObjectParameter("ho_Descripcion", ho_Descripcion) :
                new ObjectParameter("ho_Descripcion", typeof(string));
    
            var ho_HoraEntradaParameter = ho_HoraEntrada != null ?
                new ObjectParameter("ho_HoraEntrada", ho_HoraEntrada) :
                new ObjectParameter("ho_HoraEntrada", typeof(string));
    
            var ho_HoraSalidaParameter = ho_HoraSalida != null ?
                new ObjectParameter("ho_HoraSalida", ho_HoraSalida) :
                new ObjectParameter("ho_HoraSalida", typeof(string));
    
            var ho_HoraSalidaAlmuerzoParameter = ho_HoraSalidaAlmuerzo != null ?
                new ObjectParameter("ho_HoraSalidaAlmuerzo", ho_HoraSalidaAlmuerzo) :
                new ObjectParameter("ho_HoraSalidaAlmuerzo", typeof(string));
    
            var ho_HoraEntradaAlmuerzoParameter = ho_HoraEntradaAlmuerzo != null ?
                new ObjectParameter("ho_HoraEntradaAlmuerzo", ho_HoraEntradaAlmuerzo) :
                new ObjectParameter("ho_HoraEntradaAlmuerzo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Horario_Result>("sp_Busqueda_Horario", tipoBusquedaParameter, busquedaParameter, ho_empresaParameter, ho_IdHorarioParameter, ho_diaSemanaParameter, ho_NombreParameter, ho_DescripcionParameter, ho_HoraEntradaParameter, ho_HoraSalidaParameter, ho_HoraSalidaAlmuerzoParameter, ho_HoraEntradaAlmuerzoParameter, error);
        }
    
        public virtual ObjectResult<sp_Busqueda_HorarioEmpleado_Result> sp_Busqueda_HorarioEmpleado(Nullable<int> tipoBusqueda, string busqueda, Nullable<short> he_empresa, Nullable<int> he_IdHorario, Nullable<int> he_diaSemana, Nullable<int> he_IdEmpleado, ObjectParameter error)
        {
            var tipoBusquedaParameter = tipoBusqueda.HasValue ?
                new ObjectParameter("TipoBusqueda", tipoBusqueda) :
                new ObjectParameter("TipoBusqueda", typeof(int));
    
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            var he_empresaParameter = he_empresa.HasValue ?
                new ObjectParameter("he_empresa", he_empresa) :
                new ObjectParameter("he_empresa", typeof(short));
    
            var he_IdHorarioParameter = he_IdHorario.HasValue ?
                new ObjectParameter("he_IdHorario", he_IdHorario) :
                new ObjectParameter("he_IdHorario", typeof(int));
    
            var he_diaSemanaParameter = he_diaSemana.HasValue ?
                new ObjectParameter("he_diaSemana", he_diaSemana) :
                new ObjectParameter("he_diaSemana", typeof(int));
    
            var he_IdEmpleadoParameter = he_IdEmpleado.HasValue ?
                new ObjectParameter("he_IdEmpleado", he_IdEmpleado) :
                new ObjectParameter("he_IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_HorarioEmpleado_Result>("sp_Busqueda_HorarioEmpleado", tipoBusquedaParameter, busquedaParameter, he_empresaParameter, he_IdHorarioParameter, he_diaSemanaParameter, he_IdEmpleadoParameter, error);
        }
    }
}
