//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NitFactura
    {
        public short nf_empresa { get; set; }
        [Required(ErrorMessage = "Nit es requerido")]
        public string nf_Nit { get; set; }
        public int nf_IdSucursal { get; set; }
        [Required(ErrorMessage = "Nombre es requerido")]
        public string nf_Nombre { get; set; }
        public string nf_Direccion { get; set; }
        public int nf_actCentral { get; set; }
        public System.DateTime nf_fechaing { get; set; }
        public Nullable<System.DateTime> nf_fechamod { get; set; }
        public string nf_usuarioing { get; set; }
        public string nf_usuariomod { get; set; }
        public string nf_maquinaing { get; set; }
        public string nf_maquinamod { get; set; }
        public int nf_estado { get; set; }
        public byte[] nf_timestamp { get; set; }
    }
}
