//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class opcion
    {
        public short op_Empresa { get; set; }
        public int op_CodigoOpcion { get; set; }
        [Required(ErrorMessage = "Nombre de opción es requerido")]
        public string op_NombreOpcion { get; set; }
        [Required(ErrorMessage = "Descripción de opción es requerido")]
        public string op_DescOpcion { get; set; }
        public int op_PadreOpcion { get; set; }
        public bool op_Autenticar { get; set; }
        public System.DateTime op_FechaIng { get; set; }
        public Nullable<System.DateTime> op_FechaMod { get; set; }
        public string op_UsuarioIng { get; set; }
        public string op_UsuarioMod { get; set; }
        public string op_MaquinaIng { get; set; }
        public string op_MaquinaMod { get; set; }
        public int op_Estado { get; set; }
        public byte[] op_timestamp { get; set; }
    }
}
