//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfilusuario
    {
        public int pu_empresa { get; set; }
        public string pu_IdSucursal { get; set; }
        public int pu_CodPerfilUsuario { get; set; }
        public int pu_codPerfil { get; set; }
        public int pu_codUsuario { get; set; }
        public System.DateTime pu_fechaing { get; set; }
        public Nullable<System.DateTime> pu_fechamod { get; set; }
        public string pu_usuarioing { get; set; }
        public string pu_usuariomod { get; set; }
        public string pu_maquinaing { get; set; }
        public string pu_maquinamod { get; set; }
        public int pu_estado { get; set; }
        public byte[] pu_timestamp { get; set; }
        public string pu_NombrePerfil { get; set; }
        public string pu_NombreUsuario { get; set; }
    }
}
