//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class perfil
    {
        public int pf_empresa { get; set; }
        public int pf_codPerfil { get; set; }
        [Required(ErrorMessage = "Nombre de perfil es requerido")]
        public string pf_nomPerfil { get; set; }
        [Required(ErrorMessage = "Descripción del perfil requerida")]
        public string pf_descPerfil { get; set; }
        public System.DateTime pf_fechaing { get; set; }
        public Nullable<System.DateTime> pf_fechamod { get; set; }
        public string pf_usuarioing { get; set; }
        public string pf_usuariomod { get; set; }
        public string pf_maquinaing { get; set; }
        public string pf_maquinamod { get; set; }
        public int pf_estado { get; set; }
        public byte[] pf_timestamp { get; set; }
    }
}
