//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public short pe_empresa { get; set; }
        public string pe_IdSucursal { get; set; }
        public int pe_IdPermiso { get; set; }
        public int pe_CodPerfil { get; set; }
        public int pe_CodigoOpcion { get; set; }
        public System.DateTime pe_FechaIng { get; set; }
        public Nullable<System.DateTime> pe_FechaMod { get; set; }
        public string pe_UsuarioIng { get; set; }
        public string pe_UsuarioMod { get; set; }
        public string pe_MaquinaIng { get; set; }
        public string pe_MaquinaMod { get; set; }
        public int pe_estado { get; set; }
        public byte[] pe_timestamp { get; set; }
        public string pe_DescPerfil { get; set; }
        public string pe_DescOpcion { get; set; }
    }
}
