//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioProductoServicio
    {
        public short pp_empresa { get; set; }
        public int pp_IdPrecProdServ { get; set; }
        public string pp_TipoPrecio { get; set; }
        public int pp_IdProdServ { get; set; }
        public decimal pp_precio { get; set; }
        public Nullable<decimal> pp_PrecioMaximo { get; set; }
        public Nullable<System.DateTime> pp_fechaVigencia { get; set; }
        public System.DateTime pp_fechaing { get; set; }
        public Nullable<System.DateTime> pp_fechamod { get; set; }
        public string pp_usuarioing { get; set; }
        public string pp_usuariomod { get; set; }
        public string pp_maquinaing { get; set; }
        public string pp_maquinamod { get; set; }
        public int pp_estado { get; set; }
        public byte[] pp_timestamp { get; set; }
    }
}
