//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public short pr_empresa { get; set; }
        public int pr_TipoProducto { get; set; }
        public int pr_IdProd { get; set; }
        public string pr_nombre { get; set; }
        public string pr_descripcion { get; set; }
        public string pr_CodigoBarras { get; set; }
        public string pr_CodigoSAP { get; set; }
        public string pr_IdMarca { get; set; }
        public byte[] pr_ImagenProd { get; set; }
        public System.DateTime pr_fechaing { get; set; }
        public Nullable<System.DateTime> pr_fechamod { get; set; }
        public string pr_usuarioing { get; set; }
        public string pr_usuariomod { get; set; }
        public string pr_maquinaing { get; set; }
        public string pr_maquinamod { get; set; }
        public int pr_estado { get; set; }
        public byte[] pr_timestamp { get; set; }
    }
}
