//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propina
    {
        public int pn_empresa { get; set; }
        public int pn_IdSucursal { get; set; }
        public int pn_IdPropina { get; set; }
        public int pn_IdOrdenPago { get; set; }
        public int pn_IdOrdenServicio { get; set; }
        public Nullable<int> pn_IdDetalleOrdenServicio { get; set; }
        public Nullable<decimal> pn_Cantidad { get; set; }
        public System.DateTime pn_fechaing { get; set; }
        public Nullable<System.DateTime> pn_fechamod { get; set; }
        public string pn_usuarioing { get; set; }
        public string pn_usuariomod { get; set; }
        public string pn_maquinaing { get; set; }
        public string pn_maquinamod { get; set; }
        public int pn_estado { get; set; }
        public byte[] pn_timestamp { get; set; }
    }
}
