//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proveedor
    {
        public short pv_empresa { get; set; }
        public int pv_proveedor { get; set; }
        [Required(ErrorMessage = "Tipo de proveedor es requerido")]
        public string pv_tipoProveedor { get; set; }
        [Required(ErrorMessage = "Primer nombre es requerido")]
        public string pv_nombre1 { get; set; }
        public string pv_nombre2 { get; set; }
        [Required(ErrorMessage = "Nit es requerido")]
        public string pv_nit { get; set; }
        public System.DateTime pv_fechaing { get; set; }
        public Nullable<System.DateTime> pv_fechamod { get; set; }
        public string pv_usuarioing { get; set; }
        public string pv_usuariomod { get; set; }
        public string pv_maquinaing { get; set; }
        public string pv_maquinamod { get; set; }
        public int pv_estado { get; set; }
        public byte[] pv_timestamp { get; set; }
    }
}
