//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaEfectivoCaja
    {
        public short sc_empresa { get; set; }
        public int sc_IdSalidaEfectivo { get; set; }
        public int sc_IdSucursal { get; set; }
        public System.DateTime sc_FechaHoraSEC { get; set; }
        public string sc_MotivoSalidaEfectivo { get; set; }
        public decimal sc_Monto { get; set; }
        public string sc_Moneda { get; set; }
        public int sc_IdAutorizacion { get; set; }
        public Nullable<int> sc_IdCierreCaja { get; set; }
        public Nullable<int> sc_ConfirmaCierreCaja { get; set; }
        public Nullable<int> sc_IdDoc { get; set; }
        public Nullable<int> sc_IdFacturaFormaPago { get; set; }
        public System.DateTime sc_fechaing { get; set; }
        public Nullable<System.DateTime> sc_fechamod { get; set; }
        public string sc_usuarioing { get; set; }
        public string sc_usuariomod { get; set; }
        public string sc_maquinaing { get; set; }
        public string sc_maquinamod { get; set; }
        public int sc_estado { get; set; }
        public byte[] sc_timestamp { get; set; }
    }
}
