//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secuencial
    {
        public int sc_empresa { get; set; }
        public int sc_codTabla { get; set; }
        public string sc_tabla { get; set; }
        public int sc_secuencial { get; set; }
        public string sc_DataBase { get; set; }
        public int sc_Centralizado { get; set; }
        public System.DateTime sc_fechaing { get; set; }
        public Nullable<System.DateTime> sc_fechamod { get; set; }
        public string sc_usuarioing { get; set; }
        public string sc_usuariomod { get; set; }
        public string sc_maquinaing { get; set; }
        public string sc_maquinamod { get; set; }
        public int sc_estado { get; set; }
        public byte[] sc_timestamp { get; set; }
    }
}
