//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieFactura
    {
        public short sf_empresa { get; set; }
        public int sf_IdSucursal { get; set; }
        public int sf_IdSerieFactura { get; set; }
        public string sf_Terminal { get; set; }
        public string sf_TipoCorrelativo { get; set; }
        public string sf_Serie { get; set; }
        public int sf_RangoInicio { get; set; }
        public int sf_RangoFinal { get; set; }
        public int sf_NoFactura { get; set; }
        public System.DateTime sf_fechaVigencia { get; set; }
        public string sf_estRegistro { get; set; }
        public System.DateTime sf_fechaing { get; set; }
        public Nullable<System.DateTime> sf_fechamod { get; set; }
        public string sf_usuarioing { get; set; }
        public string sf_usuariomod { get; set; }
        public string sf_maquinaing { get; set; }
        public string sf_maquinamod { get; set; }
        public int sf_estado { get; set; }
        public byte[] sf_timestamp { get; set; }
    }
}
