//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public short sv_empresa { get; set; }
        public int sv_TipoServicio { get; set; }
        public int sv_IdServicio { get; set; }
        public string sv_nombre { get; set; }
        public string sv_descripcion { get; set; }
        public int sv_duracionServicio { get; set; }
        public System.DateTime sv_fechaing { get; set; }
        public Nullable<System.DateTime> sv_fechamod { get; set; }
        public string sv_usuarioing { get; set; }
        public string sv_usuariomod { get; set; }
        public string sv_maquinaing { get; set; }
        public string sv_maquinamod { get; set; }
        public int sv_estado { get; set; }
        public byte[] sv_timestamp { get; set; }
    }
}
