//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public short ts_empresa { get; set; }
        public int ts_IdTipoServicio { get; set; }
        public string ts_nombre { get; set; }
        public string ts_descripcion { get; set; }
        public Nullable<int> ts_padre { get; set; }
        public string ts_Coordinacion { get; set; }
        public string ts_CuentaSAP { get; set; }
        public System.DateTime ts_fechaing { get; set; }
        public Nullable<System.DateTime> ts_fechamod { get; set; }
        public string ts_usuarioing { get; set; }
        public string ts_usuariomod { get; set; }
        public string ts_maquinaing { get; set; }
        public string ts_maquinamod { get; set; }
        public int ts_estado { get; set; }
        public byte[] ts_timestamp { get; set; }
    }
}
