//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProducto
    {
        public short tp_empresa { get; set; }
        public int tp_IdTipoProducto { get; set; }
        public string tp_ClasificacionTP { get; set; }
        public string tp_nombre { get; set; }
        public string tp_descripcion { get; set; }
        public Nullable<int> tp_padre { get; set; }
        public System.DateTime tp_fechaing { get; set; }
        public Nullable<System.DateTime> tp_fechamod { get; set; }
        public string tp_usuarioing { get; set; }
        public string tp_usuariomod { get; set; }
        public string tp_maquinaing { get; set; }
        public string tp_maquinamod { get; set; }
        public int tp_estado { get; set; }
        public byte[] tp_timestamp { get; set; }
    }
}
