//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Usuario
    {
        public short us_empresa { get; set; }
        public int us_IdSucursal { get; set; }
        public int us_codUsuario { get; set; }
        [Required(ErrorMessage = "Usuario es requerido")]
        public string us_usuario { get; set; }
        [Required(ErrorMessage = "Nombre de usuario es requerido")]
        public string us_nombre { get; set; }
        [Required(ErrorMessage = "Contraseña es requeridad")]
        [DataType(DataType.Password)]
        public string us_password { get; set; }
        public string us_estUsuario { get; set; }
        public Nullable<int> us_IdEmpleado { get; set; }
        public int us_resetPass { get; set; }
        public System.DateTime us_fechaing { get; set; }
        public Nullable<System.DateTime> us_fechamod { get; set; }
        public string us_usuarioing { get; set; }
        public string us_usuariomod { get; set; }
        public string us_maquinaing { get; set; }
        public string us_maquinamod { get; set; }
        public int us_estado { get; set; }
        public byte[] us_timestamp { get; set; }
    }
}
