//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGrupo3S.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UltimosTelefonos
    {
        public short Empresa { get; set; }
        public int Asociado { get; set; }
        public string TelCelular { get; set; }
        public string TelCasa { get; set; }
        public string TelTrabajo { get; set; }
    }
}
